### ISSUE TITLE
Python module evaluation crashes with multiline docstring

### ISSUE THREAD

**Issue by carocad** [LightTable/LightTable#1889] opened 2015-04-14 09:16 UTC
When evaluating a module which contains a multiline docstring and a global function call, Lighttable prints the following error:
    """
      ^
SyntaxError: EOF while scanning triple-quoted string literal

I tested my code on a python interpreter on the terminal and it runs without any problem. Furthermore, this error doesn't stop Lighttable from executing the code, as I can see the result on the console.

From what I have traced, the bug only happens if the module has a multiline docstring with a global function evaluation. If only one of those happens, the bug doesn't happen. Also, if only the global function is evaluated, the bug doesn't happen either.

Attached you can find two screenshot of the code that shows this error (sorry I couldn't make it fit in one
![captura de pantalla de 2015-04-14 11 14 44](https://cloud.githubusercontent.com/assets/10408729/7133841/8453070c-e297-11e4-97ec-3d091c7bba80.png)
![captura de pantalla de 2015-04-14 11 14 33](https://cloud.githubusercontent.com/assets/10408729/7133846/8899b9b4-e297-11e4-8054-6d6c3a614d47.png)

)

Hope it helps,

Cheers

**Comment by bilderbuchi** [comment] 2015-04-23 08:32
I think this is a duplicate of #1503

**Comment by kenny-evitt** [comment] 2015-04-30 14:27
@carocad re-open this if this isn't a duplicate of #1503.

**Closed** 2015-04-30 14:27 UTC
