### ISSUE TITLE
REPL fails to connect after lein ring uberjar is run from the console like issue #1173

### ISSUE THREAD

**Issue by tianhao** [LightTable/LightTable#1880] opened 2015-03-19 09:45 UTC
This issue is still on the latest verstion 0.7.2 for mac os

> lein new compojure-app testconnect      ; then LT add connecttion success
> lein ring uberjar      ; then LT add connecttion fail, like issue https://github.com/LightTable/LightTable/issues/1173
> lein clean      ;; then add connecttion success

**Comment by rundis** [comment] 2015-03-27 19:19
Can reproduce the issue with the project and description above. 
This project: https://github.com/rundis/acme-buddy/tree/master/acme-auth works fine with regardless of uberjaring or not (tried with and with aot  as well).

**Comment by rundis** [comment] 2015-03-27 19:52
Right... so it's a classpath problem with tools.reader.
Modifying the project.clj for the testconnect project generated above to something like:
```clojure
  [org.clojure/tools.reader "0.8.1"]
  [compojure "1.1.6" :exclusions [[org.clojure/tools.reader]]]
```
and voila connection works as expected. Upping the compojure dependency to say version 1.2.1 helps as well  (since that has a transitive dep to a tools.reader version.

I guess the root problem is classloader isolation when implementing nrepl middleware. Light Table is not alone here (ref https://github.com/clojure-emacs/refactor-nrepl/issues/20)

@cldwalker @ibdknox : Any thoughts on how LT might better address the wider issue on classloader isolation between the projects and LT's nrepl middleware ?

**Comment by ibdknox** [comment] 2015-04-06 23:18
@rundis I know very little about the JVM's classloader stuff unfortunately and I was never able to figure out a way to have LT's stuff sectioned off from the project's process. :(

**Comment by rundis** [comment] 2015-04-18 09:14
One possible solution for classloader isolation here: https://github.com/LightTable/Clojure/issues/44

**Comment by rundis** [comment] 2015-07-02 08:02
I think https://github.com/LightTable/Clojure/pull/48 pretty much addresses this issue properly.

**Comment by kenny-evitt** [comment] 2015-07-02 13:09
This is a duplicate of #1052.

**Closed by kenny-evitt** 2015-07-02 13:09 UTC
