### ISSUE TITLE
"Failed to open path" when running from USB drive on Windows 64 bit

### ISSUE THREAD

**Issue by yardstudio** [LightTable/LightTable#2332] opened 2017-04-16 18:52 UTC
## Report a Bug
LightTable running from USB drive  I:\PortableAPPS\lighttable-0.8.1-windows

> Failed to open path 'C:\Users\jaro\AppData\Roaming\LightTable\ltcache\default.clj' with error: Error: ENOENT: no such file or directory, open 'C:\Users\jaro\AppData\Roaming\LightTable\ltcache\default.clj'

### Steps to Reproduce

 1. place LightTable to USB drive_
 2. run it from USB drive

### Environment

Windows 7 64 bit

Light Table version
0.8.1
Binary version
0.34.5
Plugins directory
C:\Users\jaro\AppData\Roaming\LightTable\plugins

**Comment by sbauer322** [comment] 2017-04-25 03:11
I was able to reproduce this with a USB drive only when `C:\Users\jaro\AppData\Roaming\LightTable\` directory is missing.

This should only happen on the first launch LT of `C:\Users\jaro\AppData\Roaming\LightTable\` or whenever that directory is missing. PR https://github.com/LightTable/LightTable/pull/2316 has been merged to address this message. The fix will be including in the upcoming LT release.

Since a fix has already been merged, and the error should not always happen, I am closing this issue. Thank you!

**Closed by sbauer322** 2017-04-25 03:11 UTC
Labels: bug
