### ISSUE TITLE
Error: http://app.kodowa.com/_fetch

### ISSUE THREAD

**Issue by sersajar** [LightTable/LightTable#2149] opened 2016-02-24 15:15 UTC
It gives me this error on the console every few seconds while I navigating through the menu or searching for plugins. How can i fix it???

Failed to load resource: the server responded with a status of 500 (Server Error): http://app.kodowa.com/_fetch

**Comment by kenny-evitt** [comment] 2016-02-24 16:21
This is a duplicate of #2148.

**Closed by kenny-evitt** 2016-02-24 16:21 UTC
