### ISSUE TITLE
Clojure: hash set literal notation exception

### ISSUE THREAD

**Issue by paulMihei** [LightTable/LightTable#2140] opened 2016-02-06 14:45 UTC
After pressing Ctrl + Shift + Enter (It's the same with Ctrl + Enter)
![image](https://cloud.githubusercontent.com/assets/4924690/12867137/e561fc0e-cce5-11e5-8a4a-3bb216e74d1a.png)

but

![image](https://cloud.githubusercontent.com/assets/4924690/12867165/b1f4b04a-cce6-11e5-8feb-191cb3706992.png)

What I have installed on my Windows 10 64bit:
![image](https://cloud.githubusercontent.com/assets/4924690/12867178/ef3e05d2-cce6-11e5-9af4-22053fcef467.png)

Plugins:
![image](https://cloud.githubusercontent.com/assets/4924690/12867208/b9a999c6-cce7-11e5-925f-08e020475c12.png)

**Comment by kenny-evitt** [comment] 2016-02-06 20:13
@paulMihei This is a duplicate of LightTable/Clojure#71. The recent versions of the Clojure plugin require a Clojure version of 1.7.0 or newer. I'm guessing your project is using an earlier version. You should be able to update the version your project uses – I just did for the project for which I ran into this and I didn't have any problems.

I'll re-open this if your issue is different than mine.

**Closed by kenny-evitt** 2016-02-06 20:13 UTC
