### ISSUE TITLE
Error when opening repl

### ISSUE THREAD

**Issue by conchis** [LightTable/LightTable#1965] opened 2015-09-02 20:35 UTC
Without any updates of changes, this following started happening every time I try to open a Clojure repl. I am not sure why it is looking for bootstrap.js. 

```
Invalid behavior: :lt.objs.sidebar.command/exec-command
Error: No protocol method IDeref.-deref defined for type null: 
    at Error (<anonymous>)
    at cljs.core.missing_protocol (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:1460:10)
    at cljs.core._deref (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2181:38)
    at cljs.core.deref (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:12879:27)
    at Function.eval (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/plugins/clojure/clojure_compiled.js:1601:544)
    at b (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6188:14)
    at a (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6234:18)
    at a (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:21134:29)
    at b (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:21138:14)
    at cljs.core.apply_to (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:6097:85)
```

**Comment by kenny-evitt** [comment] 2015-09-05 22:25
@conchis *bootstrap.js* is the core Light Table code (compiled from the ClojureScript source into JavaScript). What version of LT are you running? What OS are you running? Please provide steps and code to reproduce this.

**Comment by MMSN** [comment] 2015-10-01 07:05
@kenny-evitt I got the same issue, LT 32, Linux Mint 17. I was following this tutorial: http://docs.lighttable.com/ , in the second step, when opening the REPL the error happened.

Sorry >.<

**Comment by kenny-evitt** [comment] 2015-10-02 00:17
@conchis I'll re-open if this is still an un-resolved issue.

**Comment by dkharlan** [comment] 2015-12-10 18:18
I have the same issue with a clean install (downloaded via lighttable.com, looks like the current version is lighttable-0.8.0-alpha-mac) on Mac OS X El Capitan:

```
Error: No protocol method IDeref.-deref defined for type null: 
    at Error (native)
    at cljs.core.missing_protocol (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:1460:77)
    at cljs.core._deref (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:2181:38)
    at cljs.core.deref (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:12879:27)
    at Function.eval (/Applications/LightTable.app/Contents/Resources/app/plugins/Clojure/clojure_compiled.js:1675:544)
    at b (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6188:14)
    at a (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6234:18)
    at a (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21155:29)
    at b (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21159:14)
    at cljs.core.apply_to (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6097:85)
```

**Comment by rundis** [comment] 2015-12-10 20:19
@dkharlan  Would you mind trying to remove (mv to a bck folder) the Light Table settings folder
should be in ~/Library/Application\ Support/LightTable. Maybe there is something in your settings/behaviors/plugins etc that is causing the problem.

**Comment by dkharlan** [comment] 2015-12-11 14:35
I tried that and still get the same error.

**Comment by dkharlan** [comment] 2015-12-14 15:13
Apologies, this might have been user error -- when I try "Instrarepl: Open a clojure instarepl" it works fine.  The issue is when I try "Instarepl: Make current edtior an instarepl"

**Comment by cldwalker** [comment] 2016-01-01 00:42
Closing as we never got a response from the original author. @dkharlan if you're still having problems with LightTable 0.8.0 and the ClojureInstarepl plugin, feel free to report it at https://github.com/LightTable/ClojureInstarepl/issues

**Closed by cldwalker** 2016-01-01 00:42 UTC
Labels: not-reproducible
