### ISSUE TITLE
LightTable doesn't maintain fullscreen on OS X

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [LightTable/LightTable#1859] opened 2015-02-16 22:58 UTC
LightTable is definitely the kind of IDE that makes more sense in fullscreen. However, on OS X, the expected behaviour is for an app to *remain* fullscreen, once you set it up that way.

LightTable, when quit, re-sets to being a windowed application, no matter how many times you fullscreen it while working. While only mildly annoying, this is behaviour that could be improved for Mac users. :P

**Comment by cldwalker** [comment] 2015-02-20 16:07
This is a duplicate of #1814

**Closed by cldwalker** 2015-02-20 16:07 UTC
