### ISSUE TITLE
Save as... bug not saving earlier saved file at different location at new location

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#1785] opened 2014-12-22 14:43 UTC
As title suggests, I am unable to take a new file, then save it somewhere, change things and then to `Save as ...` on another location. There simply won't be a file. I posted about this earlier but perhaps either someone thought it resolved, or the earlier cleanup had it moved, either way this bug is still active  it seems and I couldn't find it in any other issues here so I'll post this one.

Reproducible: always (at least on my box, can anyone else confirm? I run ArchLinux with Xcfe desktop at the moment).

**Comment by mwil** [comment] 2015-02-20 10:28
I ran into the same problem on OSX 10.9. Tried to save a copy to a different location and continued working with the original file, but the backup was never created. Seems like a quite critical bug to me.

**Comment by cldwalker** [comment] 2016-01-16 06:54
Following @clojens instructions I can't reproduce this on osx 10.10 with latest LT. The tab title updates correctly if saved to a different file. I'm guessing this was buggy behavior from node-webkit days. Will close in a few days unless others can reproduce with latest LT and have any more specifics

**Comment by cldwalker** [comment] 2016-01-26 06:21
Closing for reasons stated above

**Closed by cldwalker** 2016-01-26 06:21 UTC
Labels: linux, not-reproducible
