### ISSUE TITLE
Error: incorrect header check     at Zlib._binding.onerror (zlib.js:295:17)

### ISSUE THREAD

**Issue by 602884291** [LightTable/LightTable#2130] opened 2016-01-22 03:19 UTC
update soft version  Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

**Comment by cldwalker** [comment] 2016-01-22 03:45
Hi. Thanks for the report. We need [reproducible steps](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs) in order to debug this. Things that would be useful to know: operating system, what version did you upgrade from, are you behind a firewall, how did you update (through LightTable or did you download a now install off the website). If we can't reproduce it, we can't fix it

**Comment by max-orhai** [comment] 2016-01-22 06:38
I'm having the same issue, updating from 0.6.7 on Ubuntu.

Steps: Open app, click update dialog button, open console after waiting for throbber.

**Comment by rundis** [comment] 2016-01-22 08:02
There are a few of similar reported issues (closed ones). It could be related with instability with the tar service from github, or it could be path lengths. Well mostly guessing. But it might be easier to track down with a little bit of error handling in deploy.cljs
https://github.com/LightTable/LightTable/blob/d2e28d25585b00fd2541ebdc2009fc9ec5b4df29/src/lt/objs/deploy.cljs#L94

**Comment by rundis** [comment] 2016-01-22 08:08
maybe we need to checksum the downloaded file or something to ensure the downloaded tar is valid ?

**Comment by cldwalker** [comment] 2016-01-22 09:15
@max-orhai Thanks for the info. I just ran an upgrade from 0.8.0 on ubuntu and didn't see this issue. It's possible this is an error that we get only when upgrading from older versions e.g. #974. If that is the case there is nothing we can do except have users upgrade. Can you drop in the full error message? Does your upgrade succeed if you reattempt?

**Comment by cldwalker** [comment] 2016-01-22 09:16
@max-orhai If it doesn't I'd recommend just downloading the latest from the website as a _lot_ has changed since 0.6.7

**Comment by max-orhai** [comment] 2016-01-22 09:23
I retried a few times, and once got a different error: a long stack trace that seemed to be complaining about a missing /usr/local/bin/LightTable/tmp directory. Sorry I didn't save that to paste here, but I doubt it would be worth fixing anyway: I eventually just reinstalled LT fresh from the 8.1 binary download, which worked fine. I agree that's a pretty big jump to handle gracefully with an auto-update, especially for a young project like this one.

**Comment by cldwalker** [comment] 2016-01-22 10:02
> I retried a few times, and once got a different error: a long stack trace that seemed to be complaining about a missing /usr/local/bin/LightTable/tmp directory.

That's a known error that we've fixed. :) Nothing to fix except having less users on older :bug:ier versions

**Comment by palfrey** [comment] 2016-01-24 15:04
Seeing the Zlib error on OS X from version 0.7.2. I'm trying to update via the LightTable menu item.

**Comment by cldwalker** [comment] 2016-01-26 06:20
Closing as there isn't anything we can do for errors on upgrading for old versions. Code base has changed too much to backport anything more than a few months back

**Closed by cldwalker** 2016-01-26 06:20 UTC
Labels: not-reproducible

**Comment by kenny-evitt** [comment] 2016-01-31 17:27
[I created an issue to look into problems with upgrades in LT.](https://github.com/LightTable/LightTable/issues/2138) Note that we're restricting this to upgrading from 0.8.0 to later versions as too much changed between 0.7.2 and 0.8.0.

**Comment by mbennette68** [comment] 2016-02-07 21:26
I just start Light Table.  Message pops up saying, "There's a newer version of Light Table!

Would you like us to download and install version 0.8.0?"  I click on, "Download and Install."  App starts updating, never stops, and Console displays error, "Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)"  Don't ever see that it actually updates, at all.

**Comment by rundis** [comment] 2016-02-07 21:38
@mbennette68: As @kenny-evitt  states above there is a known issue with upgrading from 0.7.2 to the newest version of Light Table (which is 0.8.1 btw). If you would be so kind to try to download the newest binary from http://lighttable.com/ and install it for your platform. Hopefully you should be good to go after that. (A lot has changed since 0.7.2 so an easy upgrade just isn't/wasn't possible)

**Comment by mbennette68** [comment] 2016-02-07 21:44
Appreciate the advise and will proceed to download new binary :)
