### ISSUE TITLE
Unresponsive after resuming from suspended system

### ISSUE THREAD

**Issue by gsscoder** [LightTable/LightTable#1914] opened 2015-06-02 09:12 UTC
I've installed it from binaries quoted **LINUX 64-BIT** supplied by **lighttable.com** (not cloning from *github.com*) and added `LightTable` startup script to my `$PATH`.
LightTable version: **0.7.2**
Binary version: **0.8.6**
Plugins directory: `/home/giacomo/.config/LightTable/plugins`

It follows some other info:
```sh
$ which LightTable
/home/giacomo/opt/LightTable/LightTable

$ uname -or
3.2.0-83-generic GNU/Linux

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"

$ tree -dL 3 $HOME/.config/LightTable
/home/giacomo/.config/LightTable
├── Cache
├── GPUCache
├── Local Storage
├── logs
├── ltcache
│   └── workspace
├── plugins
│   └── LightTable-Go
│       ├── client
│       ├── codemirror
│       └── src
└── User
    └── src
        └── lt

$ original_conf=$HOME/.config/LightTable/User/user.behaviors~
$ new_conf=$HOME/.config/LightTable/User/user.behaviors
$ git diff --no-index $original_conf $new_conf
diff --git a/home/giacomo/.config/LightTable/User/user.behaviors~ b/home/giacomo/.config/LightTable/User/user.behaviors
index 1d7c835..f109982 100644
--- a/home/giacomo/.config/LightTable/User/user.behaviors~
+++ b/home/giacomo/.config/LightTable/User/user.behaviors
@@ -29,3 +29,7 @@
  ;;  [:app :-lt.objs.intro/show-intro]
 ]
 
+:editor.go [(:lt.plugins.go/change-gofmt-command "gofmt -w=true")
+            (:lt.plugins.go/change-gobuild-command "go build -o")
+            (:lt.plugins.go/change-gorun-command "go run")
+            (:lt.plugins.go/change-gotest-command "go test")]
\ No newline at end of file
```
I start the program from **Konsole** terminal with command `LightTable &` then I open some file from my workspace (automatically obtained starting it from a local source tree using `LightTable . &` the first time).

Beyond this, everything works fine and I've to take chance to congratulate you for the *excellent job* (and also for *sharing it*).

But if I suspend my Ubuntu box, when I came back LightTable window is dark and unresponsive. It can't be closed and must killed with `pkill ltbin`.

This is not a really serious issue and can be superseded closing the program before suspending the operating system. However I thought it would be useful for you to know.

**Comment by gsscoder** [comment] 2015-06-08 15:23
I've made a mistake in configuring the Go/Lang plugin, anyway solving this didn't solved the problem...

**Comment by sashton** [comment] 2015-06-25 01:29
I've been unable to reproduce this on my machine. Although I am using the latest from the atom-shell branch. 

```
$ uname -or
3.11.0-26-generic GNU/Linux

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=13.10
DISTRIB_CODENAME=saucy
DISTRIB_DESCRIPTION="Ubuntu 13.10"
```

**Comment by kenny-evitt** [comment] 2015-06-25 13:26
@gsscoder Would you try to reproduce this using the *atom-shell* branch?

**Comment by gsscoder** [comment] 2015-06-25 14:04
@sashton, I think there's no problem in doing it. :+1: 

I'll post back here, when done.

**Comment by gsscoder** [comment] 2015-06-28 15:46
Sorry, but I've never build **LightTable** before. This is what I get aftet `./script/build.sh`:
```bash
npm WARN package.json download-electron@0.1.0 No README.md file found!
npm http GET https://registry.npmjs.org/grunt-cli
npm http 200 https://registry.npmjs.org/grunt-cli
npm http GET https://registry.npmjs.org/grunt-cli/-/grunt-cli-0.1.13.tgz
npm http 200 https://registry.npmjs.org/grunt-cli/-/grunt-cli-0.1.13.tgz
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/resolve
npm http 200 https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.3.tgz
npm http 200 https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz
npm http 200 https://registry.npmjs.org/resolve
npm http GET https://registry.npmjs.org/resolve/-/resolve-0.3.1.tgz
npm http 200 https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.3.tgz
npm http 200 https://registry.npmjs.org/resolve/-/resolve-0.3.1.tgz
npm http 200 https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/lodash
npm http 200 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/abbrev/-/abbrev-1.0.7.tgz
npm http 200 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm http 200 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/glob/-/glob-3.2.11.tgz
npm http 200 https://registry.npmjs.org/abbrev/-/abbrev-1.0.7.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz
npm http 200 https://registry.npmjs.org/glob/-/glob-3.2.11.tgz
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 200 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
npm http 200 https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.6.4.tgz
npm http 200 https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz
npm http 200 https://registry.npmjs.org/lru-cache/-/lru-cache-2.6.4.tgz
npm WARN prefer global grunt-cli@0.1.13 should be installed with -g
grunt-cli@0.1.13 node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
npm WARN package.json download-electron@0.1.0 No README.md file found!
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-download-electron
npm http 200 https://registry.npmjs.org/grunt-download-electron
npm ERR! Error: No compatible version found: grunt-download-electron@'^2.0.0'
npm ERR! Valid install targets:
npm ERR! ["2.0.0","2.0.1","2.1.0","2.1.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:674:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:589:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-85-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/giacomo/opt/LightTable/shell
npm ERR! node -v v0.8.18
npm ERR! npm -v 1.2.2
npm http 200 https://registry.npmjs.org/grunt
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/giacomo/opt/LightTable/shell/npm-debug.log
npm ERR! not ok code 0
```

The problem is that without building it, I'm unable to check for the issue again. Any help?

**Comment by kenny-evitt** [comment] 2015-06-28 18:40
@gsscoder, would you try upgrading to the latest Node.js and npm? Follow the instructions on the Node.js website as the version available thru the package manager for your distro is probably a much older version (if not the one you already have installed).

**Comment by gsscoder** [comment] 2015-06-28 18:58
@kenny-evitt, yes in my linux box I still run **Ubuntu 12**... I'll post here after updating **NodeJS**. 

Thank you.

**Comment by cldwalker** [comment] 2015-12-02 05:19
Closing as no else has been able to reproduce this, myself included on a ubuntu VM. @gsscoder Happy to reopen if you try this on the latest 0.8.0-alpha and  provide reproducible steps

**Closed by cldwalker** 2015-12-02 05:19 UTC
Labels: linux
