### ISSUE TITLE
Build fails with "Could not transfer artifact..." on armhf

### ISSUE THREAD

**Issue by nonnymoose** [LightTable/LightTable#2224] opened 2016-06-25 16:15 UTC
### Steps to Reproduce

I downloaded leiningen exactly as described and node 4.2.6 and npm 3.5.2 from my package manager. I used `update-alternatives` to link the node command to nodejs. When I ran `script/build.sh`, it failed with the errors below.

### Environment

| Info                             | Details |
| -------------------------------- | ------- |
| Light Table version              |0.8.1         |
| Operating system                 |Ubuntu Mate 16.04, `Linux RaspberryPi 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l armv7l armv7l GNU/Linux`         |

### Error Messages
```
$ script/build.sh
OpenJDK Zero VM warning: TieredCompilation is disabled in this release.
Could not transfer artifact lein-cljsbuild:lein-cljsbuild:pom:1.0.1 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
Could not transfer artifact lein-codox:lein-codox:pom:0.9.0 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
/usr/local/src/LightTable-0.8.1/deploy/electron /usr/local/src/LightTable-0.8.1
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated wrench@1.5.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
download-electron@0.1.0 /usr/local/src/LightTable-0.8.1/deploy/electron
  grunt@0.4.5 
  async@0.1.22 
  coffee-script@1.3.3 
  colors@0.6.2 
  dateformat@1.0.2-1.2.3 
  eventemitter2@0.4.14 
  exit@0.1.2 
  findup-sync@0.1.3 
   glob@3.2.11 
    inherits@2.0.1 
    minimatch@0.3.0 
   lodash@2.4.2 
  getobject@0.1.0 
  glob@3.1.21 
   graceful-fs@1.2.3 
   inherits@1.0.2 
  grunt-legacy-log@0.1.3 
   grunt-legacy-log-utils@0.1.1 
    lodash@2.4.2 
    underscore.string@2.3.3 
   lodash@2.4.2 
   underscore.string@2.3.3 
  grunt-legacy-util@0.2.0 
  hooker@0.2.3 
  iconv-lite@0.2.11 
  js-yaml@2.0.5 
   argparse@0.1.16 
    underscore@1.7.0 
    underscore.string@2.4.0 
   esprima@1.0.4 
  lodash@0.9.2 
  minimatch@0.2.14 
   lru-cache@2.7.3 
   sigmund@1.0.1 
  nopt@1.0.10 
   abbrev@1.0.9 
  rimraf@2.2.8 
  underscore.string@2.2.1 
  which@1.0.9 
 grunt-cli@0.1.13 
  resolve@0.3.1 
 grunt-download-electron@2.1.4 
   decompress-zip@0.0.4 
    binary@0.3.0 
     buffers@0.1.1 
     chainsaw@0.1.0 
       traverse@0.3.9 
    mkpath@0.1.0 
    nopt@2.1.2 
    q@0.9.7 
    readable-stream@1.1.14 
     core-util-is@1.0.2 
     isarray@0.0.1 
     string_decoder@0.10.31 
    touch@0.0.2 
   github-releases@0.3.2 
    minimatch@0.2.12 
    optimist@0.4.0 
     wordwrap@0.0.3 
    prettyjson@1.1.3 
     colors@1.1.2 
     minimist@1.2.0 
    request@2.51.0 
      aws-sign2@0.5.0 
      bl@0.9.5 
       readable-stream@1.0.34 
      caseless@0.8.0 
      combined-stream@0.0.7 
       delayed-stream@0.0.5 
      forever-agent@0.5.2 
      form-data@0.2.0 
       async@0.9.2 
       mime-types@2.0.14 
         mime-db@1.12.0 
      hawk@1.1.1 
       boom@0.4.2 
       cryptiles@0.2.2 
       hoek@0.9.1 
       sntp@0.2.4 
      http-signature@0.10.1 
       asn1@0.1.11 
       assert-plus@0.1.5 
       ctype@0.5.3 
      json-stringify-safe@5.0.1 
      mime-types@1.0.2 
      node-uuid@1.4.7 
      oauth-sign@0.5.0 
      qs@2.3.3 
      stringstream@0.0.5 
      tough-cookie@2.2.2 
      tunnel-agent@0.4.3 
   progress@1.1.2 
   wrench@1.5.4

npm WARN download-electron@0.1.0 No description
npm WARN download-electron@0.1.0 No repository field.
npm WARN download-electron@0.1.0 No license field.
Running "download-electron" task
downloading [===================] 100% 0.0s
/usr/local/src/LightTable-0.8.1
OpenJDK Zero VM warning: TieredCompilation is disabled in this release.
Could not transfer artifact lein-cljsbuild:lein-cljsbuild:pom:1.0.1 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
Could not transfer artifact lein-codox:lein-codox:pom:0.9.0 from/to central (https://repo1.maven.org/maven2/): java.lang.IllegalStateException
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

As far as I can tell, I am _not_ behind a proxy, as I am on a home network.
Any help would be appreciated. I _really_ want a code editor on the Raspberry Pi!

**Comment by kenny-evitt** [comment] 2016-06-25 18:13
@nonnymoose I think I've seen errors like that myself and that they were just intermittent issues with downloading from Maven. Try running the build script again when you have a chance and let me know whether it works.

**Comment by nonnymoose** [comment] 2016-06-26 14:16
@kenny-evitt Unfortunately that was my _third_ time trying it.

**Comment by kenny-evitt** [comment] 2016-06-27 13:20
@nonnymoose I can't reproduce this. I also just noticed that, according to the output in your comment, the build is attempting to download *lein-cljsbuild* and *lein-codox* from Maven ("central") instead of Clojars. I'm guessing your Leiningen configuration is not the same as mine.

Don't be discouraged by my closing this issue. I'm just indicating to other contributors that there's nothing really to do for this until we can reproduce your problem. Just keep commenting here with new info and I'll follow-up when I can.

**Closed by kenny-evitt** 2016-06-27 13:20 UTC
Labels: not-reproducible

**Comment by nonnymoose** [comment] 2016-06-28 13:50
@kenny-evitt  Is there a way for me to modify my configuration such that it is the same as yours?
Or at least get it and show it to you?

**Comment by kenny-evitt** [comment] 2016-06-29 00:18
@nonnymoose How'd you install Leiningen? And what version of Leiningen is installed? You can check the version by running `lein -v`.

**Comment by rundis** [comment] 2016-06-29 07:26
also did you create a ~/profiles.clj and if so does it contain anything related to repositories ?

**Comment by nonnymoose** [comment] 2016-07-04 16:08
@rundis I did not create a ~/.profiles.clj

@kenny-evitt `lein -v` returns the following:
```
OpenJDK Zero VM warning: TieredCompilation is disabled in this release.
Leiningen 2.6.1 on Java 1.8.0_91 OpenJDK Zero VM
```

**Comment by kenny-evitt** [comment] 2016-07-05 13:39
@nonnymoose I can't find anyone else reporting or discussing your exact issue. Would you mind reporting this upstream to Leiningen? Here's their GitHub repo:

 - [technomancy/leiningen: Automate Clojure projects without setting your hair on fire.](https://github.com/technomancy/leiningen)
