### ISSUE TITLE
Error opening console for first-time installs

### ISSUE THREAD

**Issue by henrywright** [LightTable/LightTable#2150] opened 2016-02-28 00:24 UTC
Hey guys,

I just installed a fresh copy of Light Table 0.8.1 on Ubuntu 14.04 and am loving it. When I click on View > Console I get the following error:

> Failed to open path '/home/username/.config/LightTable/ltcache/default.clj' with error: Error: ENOENT: no such file or directory, open '/home/username/.config/LightTable/ltcache/default.clj'

**Comment by Berkana** [comment] 2016-03-01 09:15
I also got this problem. I'm using the most recent version of MacOS X.

**Comment by naomik** [comment] 2016-03-08 17:58
:+1: Same for me on OS X

**Comment by kenny-evitt** [comment] 2016-03-09 02:23
@henrywright @Berkana @naomik Where are you seeing the error? In the console?

I can't reproduce this on my Mac [F].

**Comment by rundis** [comment] 2016-03-09 07:37
Hm not able to reproduce either. Even after deleting the ltcache directory.
Does it help if you create the dir manually (and optionally an empty default.clj in the appropriate location) ?

**Comment by henrywright** [comment] 2016-03-09 11:06
@kenny-evitt it looks as though it's showing inside the console.

**Comment by henrywright** [comment] 2016-03-09 11:10
@rundis I thought let me try clicking View > Console again (before I try creating the dir manually as you suggested). Now I see something different. I no longer get the error message, just a blank console. I assume that's what I should be seeing?

**Comment by rundis** [comment] 2016-03-09 13:41
@henrywright Unless there is something actually logged to the console, yeah !
1. try opening a new tab (cmd/ctrl + n) 
2. cmd/ctrl + enter 
3. Editor: Set current editor syntax 
4. Select say JavaScript
5. Enter something like `console.log("hello")`
6. Eval the line (cmd/ctrl + enter with the cursor placed at the end of the line)

you should see hello in the console :-)

**Comment by henrywright** [comment] 2016-03-09 14:55
@rundis doing those steps, I get

> evalresult[eval1][1]: hello

**Comment by rundis** [comment] 2016-03-09 15:03
@henrywright which is what it should be. So your console is working as expected.

**Comment by henrywright** [comment] 2016-03-09 15:04
Yes, it does seem to be working now. Thanks for your help.

**Comment by rundis** [comment] 2016-03-09 15:07
No prob. 
@Berkana @naomik Are you able to get the console working properly on subsequent tries (ie is the error message just shown once/first time you tried to display the console) ?

**Comment by Berkana** [comment] 2016-03-10 21:24
Here's what I see when I try to run some code:

![screen shot 2016-03-10 at 1 03 20 pm](https://cloud.githubusercontent.com/assets/1445825/13685045/72517f62-e6c3-11e5-8cab-e68c045689c3.png)

**Comment by kenny-evitt** [comment] 2016-03-11 15:45
@Berkana That's a different issue but try <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> to evaluate the whole file. Or, first evaluate the first form with <kbd>Cmd</kbd>+<kbd>Enter</kbd> and then evaluate the second fom with the same shortcut.

**Comment by naomik** [comment] 2016-03-16 16:31
@rundis I've never used lighttable so I'm not sure if it's working correctly or not. When I open the console, it just appears empty now. I'm working with ES6 and transpiliation via babel so I don't know if that's a further issue. I kinda just gave up because I couldn't find a clear way to run my project.

**Comment by rundis** [comment] 2016-03-16 16:40
I think the console work fine. The message reported above (which displays in the console btw), i managed to get by wiping out my lt settings folder. I think it's just bad handling of new clean installations (/not proper check if the file exists the first time).

**Comment by naomik** [comment] 2016-03-16 16:55
@rundis are people using lighttable with other build tools like babel/webpack?

**Comment by rundis** [comment] 2016-03-16 17:22
@naomik I can't say really. But the js/node support in Light Table hasn't had much love for quite some time. We could sure use a helping hand on making the js experience in LT more up to scratch.
I don't work much with JavaScript (rather use ClojureScript and lately Elm tbh)

this is rather OT, so I suggest trying out the forum 
https://groups.google.com/forum/#!forum/light-table-discussion
or gitter: 
https://gitter.im/LightTable/LightTable

**Comment by 1j01** [comment] 2016-04-05 16:17
:+1: I got this error in the Console running LT 0.8.1 on Windows 10 for the first time. That's the trifecta of operating systems, so this is definitely a Cross-Platform Bug™
I was also expecting some kind of command-line interface (whether JavaScript, ClojureScript, or shell) which led me to the "console failed to open" train of thought, but I guess it's just for output.
Maybe this issue should probably be renamed.

**Comment by kenny-evitt** [comment] 2016-04-05 19:47
@1j01 Which error did you get? The error mentioned in the original comment?

**Comment by 1j01** [comment] 2016-04-05 20:29
@kenny-evitt Yes.

**Comment by kenny-evitt** [comment] 2016-04-09 22:22
@1j01 Does the file mentioned not exist on your computer?

**Comment by 1j01** [comment] 2016-04-10 03:29
@kenny-evitt It does now presumably, because it only happened on the first launch.

**Comment by kenny-evitt** [comment] 2016-04-10 04:19
@1j01 Thanks. That would be the next thing for someone to try then – deleting that directory and then opening LT.

**Comment by sbauer322** [comment] 2016-09-05 23:53
> Failed to open path '/home/username/.config/LightTable/ltcache/default.clj' with error: Error: ENOENT: no such file or directory, open '/home/username/.config/LightTable/ltcache/default.clj'

For what it is worth, the above message occurs on startup if `default.clj` is missing from ltcache on Ubuntu 16.04. When this happens, it appears `default.clj` is created afterwards, as well as `workspace` folder in `ltcache`. Subsequent starts do not have this message.

If there are no objections (and if I understand the issue correctly) I am inclined to rename the issue. Let me know if you feel otherwise.

**Comment by vbauer** [comment] 2017-01-29 12:36
I have the same problem on macOS Sierra 10.12.3:

> Failed to open path '/Users/vbauer/Library/Application Support/LightTable/ltcache/default.clj' with error: Error: ENOENT: no such file or directory, open '/Users/vbauer/Library/Application Support/LightTable/ltcache/default.clj'

**Comment by sbauer322** [comment] 2017-02-06 03:02
PR #2316 has been merged.

**Closed by sbauer322** 2017-02-06 03:02 UTC
Labels: bug, in progress
