### ISSUE TITLE
Map destructuring of rest arguments not compiling in Instarepl

### ISSUE THREAD

**Issue by mkcmkc** [LightTable/LightTable#1888] opened 2015-04-13 23:19 UTC
Putting the following code in an Instarepl
```clojure
(defn get-date [& {:keys [date] :or {date (java.util.Date.)}}]
  date)
```
generates
```plain
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: java.util.Date., compiling:(null:5:1)
```
However, if I put it in `lein repl` it works without a problem. 

I am running OS X 10.10.3 with LightTable 0.7.2 (binary version 0.8.4).

**Comment by cldwalker** [comment] 2015-04-14 13:30
Thanks for the report. This is a duplicate of #1626

**Closed by cldwalker** 2015-04-14 13:30 UTC
