### ISSUE TITLE
Can't connect to NodeJS instance 0.4.1

### ISSUE THREAD

**Issue by warnero** [LightTable/LightTable#497] opened 2013-05-02 15:45 UTC
I first tried just launching and connecting that failed, then managed to get it started via the command-line and instead of failing completely it now tells me that the Node process suddenly quit and to check the console. I've been going through the console logs but don't know what I'm looking for and nothing pops up. Is there a specific log file to look at? I tried the lighttable server.log but there didn't seem to be much in there (and nothing new when I tried to connect, just a netty error).

Really would love to start using this for my Node development so any help is greatly appreciated!

**Comment by robjens** [comment] 2015-04-16 19:03
I can confirm that LT is still affected (esp. on the mongoose part). First project breaks, I had it fail on `bcrypt` bindings (node-gyp) pilwon/ultimate-seed#54 this exception message. However it also contains mongoose.

Next I tried **clean slate** (`mkdir foo; cd $-; npm init; npm i coffee-script; echo "var coffee = require('coffee-script');" > index.js; node index.js;`) then tried LT everything works connecting properly to `index.js`

Now if I added `mongoose` however, as soon as simple require that project, LT breaks: 

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
```

**Comment by robjens** [comment] 2015-04-16 19:18
P.s. I can share some of the code of the original project failing, it highlights where it goes wrong anyway, if it is of any use (I hope):

```
Error: Could not locate the bindings file. Tried:
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/build/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/build/Debug/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/build/Release/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/out/Debug/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/Debug/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/out/Release/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/Release/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/build/default/bcrypt_lib.node
 → /home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/compiled/0.12.2/linux/x64/bcrypt_lib.node
    at bindings (/home/foo/bar/api/node_modules/bcrypt/node_modules/bindings/bindings.js:88:9)
    at /home/foo/bar/api/node_modules/bcrypt/bcrypt.js:3:35
    at Object.exports.runInContext (vm.js:64:17)
    at sbRequire (/opt/LightTable/plugins/javascript/node/ltnodeclient.js:99:10)
    at req (/opt/LightTable/plugins/javascript/node/ltnodeclient.js:79:12)
    at /home/foo/bar/api/player/model.js:4:16
    at /home/foo/bar/api/player/model.js:859:3
    at Object.exports.runInContext (vm.js:64:17)
    at sbRequire (/opt/LightTable/plugins/javascript/node/ltnodeclient.js:99:10)
    at req (/opt/LightTable/plugins/javascript/node/ltnodeclient.js:79:12)
```
The bindings directory (`node_modules/bindings` inside `bcrypt`) does not have a `build/` directory. The file it looks for is actually inside the `build/` directory from bcrypt, not bindings. However, from the cli, the project just runs fine as it is.

Next is the code it kicks off, nothing special I guess:

```
// line 4
  var bcrypt = require("bcrypt"),
// line 859
})();

module.exports = player;
```

Last line 859 referenced in stack trace shows closing. Anyway as Chris mentioned the problem is known, not sure how much this contributes but just to inform, the problem isn't limited to `mongoose` and affects `bcrypt` as well (although I'm fairly sure they have a problem too since the build paths don't seem correct, or at least where it seems to think the compiled files are).

**Comment by kenny-evitt** [comment] 2015-06-23 20:29
@robjens I'm willing to look into this further if you can share a minimal project with which you can reproduce it.

Also, if you would, please build and run the *atom-shell* branch version and test connecting to your projects with it.

**Comment by kenny-evitt** [comment] 2015-07-14 00:50
@robjens The *master* branch is now running on Atom; please build that if you can.

**Comment by niedzielski** [comment] 2015-08-29 19:18
I believe I'm seeing the same issue on Linux using the prebuilt 0.7.2 binary and master, 686c9b1. I get the following error when trying to connect to server.js[0]:

    server.js[stderr]:
    /home/stephen/opt/LightTable/builds/lighttable-0.8.0-linux/resources/app/plugins/Javascript/node/ltnodeclient.js:99
          vm.runInContext(cleanCode(fs.readFileSync(path)), sb, path);
             ^
    SyntaxError: Illegal return statement
        at /home/stephen/dev/wmf/restbase/mobileapps/server.js:12:1
        at sbRequire (/home/stephen/opt/LightTable/builds/lighttable-0.8.0-linux/resources/app/plugins/Javascript/node/ltnodeclient.js:99:10)
        at init (/home/stephen/opt/LightTable/builds/lighttable-0.8.0-linux/resources/app/plugins/Javascript/node/ltnodeclient.js:121:3)
        at Socket.<anonymous> (/home/stephen/opt/LightTable/builds/lighttable-0.8.0-linux/resources/app/plugins/Javascript/node/ltnodeclient.js:20:5)
        at Socket.EventEmitter.emit (events.js:117:20)
        at Object.afterConnect [as oncomplete] (net.js:883:10)

[0] The project is fully open source. http://git.wikimedia.org/blob/mediawiki%2Fservices%2Fmobileapps/HEAD/server.js

**Comment by kenny-evitt** [comment] 2015-09-02 00:03
@niedzielski Thanks; an example should hopefully make fixing this easier. We're currently working on the next release but, even after it's done, I'm not sure when someone can look at this.

**Comment by niedzielski** [comment] 2015-09-02 03:56
@kenny-evitt, thanks! I don't have bandwidth to help develop a fix but I would be happy to help test one when it does come along.

**Comment by macramole** [comment] 2015-10-13 18:47
yep, getting the same problem using the locomotive library for nodejs
     
```
/mnt/stuff/Code/nodejs/muntref/taggeador/node_modules/locomotive/node_modules/actionrouter/node_modules/methods/index.js:9
  return;
  ^^^^^^

SyntaxError: Illegal return statement
    at Object.exports.runInContext (vm.js:43:16)
    at sbRequire (/home/candida/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:99:10)
    at req (/home/candida/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:79:12)
    at /mnt/stuff/Code/nodejs/muntref/taggeador/node_modules/locomotive/node_modules/actionrouter/lib/router.js:4:15
    at Object.exports.runInContext (vm.js:44:17)
    at sbRequire (/home/candida/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:99:10)
    at req (/home/candida/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:79:12)
    at /mnt/stuff/Code/nodejs/muntref/taggeador/node_modules/locomotive/node_modules/actionrouter/lib/index.js:4:18
    at Object.exports.runInContext (vm.js:44:17)
    at sbRequire (/home/candida/.config/LightTable/plugins/Javascript/node/ltnodeclient.js:99:10)
```

**Comment by cldwalker** [comment] 2016-01-13 06:57
@niedzielski issue seems separate and I've made https://github.com/LightTable/Javascript/issues/18 for it
Closing issue as we don't have reproducible steps. If still interested, please reopen it [here](https://github.com/LightTable/Javascript/issues) with reproducible steps as demonstrated in https://github.com/LightTable/Javascript/issues/18

**Closed by cldwalker** 2016-01-13 06:57 UTC
Labels: nodejs
