### ISSUE TITLE
LightTable 0.8.0-alpha crashes randomly on Windows

### ISSUE THREAD

**Issue by KrisDM** [LightTable/LightTable#2041] opened 2015-11-15 15:32 UTC
I have had several crashes, seemingly at random moments, with the current version of LightTable for Windows (64-bit), using it with Julia. The editor window goes completely white and there is no more access to the opened files. I cannot save the opened files and have to open the Task monitor and kill the process. I have no idea what causes it: it has happened when I am not working in the window and return to it after a period of inaction, but just now it also happened as I was typing in an opened file in LightTable itself. I know this won't help you reproduce the error, but because it seems so random I don't know what I can do to narrow down the causes (nor do I get any warnings or error messages of any kind).

I have lost quite a bit of hours of work because of these crashes and will now stop using LightTable until a more stable version comes out.

**Comment by kenny-evitt** [comment] 2015-11-15 19:55
@KrisDM What version of Windows are you running? We've had several reports of problems with Windows 8 and Windows 10 but I only have access to Windows 7 computers so I haven't been able to investigate directly.

We've also had reports of problems – [here](https://github.com/LightTable/LightTable/issues/1750#issuecomment-143592252) and [here](https://github.com/LightTable/LightTable/issues/1088#issuecomment-60063318) are two such comments – that seem to be related to the Julia plugin itself.

If you can share a (minimal) repo that I could use to try and reproduce these problems, that would be great.

**Comment by cldwalker** [comment] 2015-11-18 23:50
> I have lost quite a bit of hours of work because of these crashes and will now stop using LightTable until a more stable version comes out.

I'm sorry to hear this. Without reproducible steps as @kenny-evitt has asked for there isn't much that we can do. I would recommend not having the Julia plugin installed first and see if that is the issue

**Comment by petterip** [comment] 2015-11-19 09:22
I'm struggling with the same issue: LightTable crashes with white window background randomly after 2-3 hours of use. I don't have Julia plugin installed. The crashes seem to happen just before LightTable is about to show a drop down list of code hints (code completion feature). I'm running LightTable on Windows 10 (64-bit) with Java 1.8.0.65.

**Comment by kenny-evitt** [comment] 2015-11-19 15:40
@petterip Is there anything in the LT log file? Check under your LT user data directory, e.g. *C:\Users\kevitt\AppData\Roaming\LightTable\logs*.

You could also try running the *LightTable.exe* from a Windows Command Prompt – maybe something will be output there when LT crashes.

It would also be helpful if you ran [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) – maybe you can spot a spike in CPU or memory utilization prior to crashes. You could keep the Chrome Developer Tools window in LT open while you're working.

Also:

 - What plugins do you have installed?
 - Is there anything that might be (even remotely) relevant to the crashes in your *user.behaviors* file?
 - What are you doing, e.g. what language and development environment are you using with LT? Are there any other elements of your development environment that are running in the background?

**Comment by kenny-evitt** [comment] 2015-12-13 05:07
I'm closing this because we haven't been able to reproduce it. We will re-open if anyone can provide more info.

**Closed by kenny-evitt** 2015-12-13 05:07 UTC
Labels: not-reproducible
