### ISSUE TITLE
Python autoindent on all forms (ctrl+a, shift-tab) messes up code returning after 2 level deep form

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#1858] opened 2015-02-12 17:51 UTC
Having found the solution to the python indent problem I experienced, I added to `user.behavior` then line `[:editor.python :lt.objs.editor/tab-settings false 4 4]` to correct indent (this can/should be added to default behaviors I guess).

However doing so I noticed another unexpected result while indenting a whole file and I'm not sure there is an easy solution without checking for an empty line: select all forms with `ctrl-a` then `shift-tab` will mess up code following a 2 level deep nested form e.g.

```python
def foo(bar):
    if (bar == "boo"): #return return here will move cursor to root level (0)
         return "weeee" # do the same here and you are stuck at 1 forever (4 spaces now)
         # keep pressing return with cursor here and it will NEVER return to 0 columns
         #...
         #...

#[x] anything here will
#       [x] be moved here once you do SHIFT-TAB

# | just as cursor here and then RETURN
#       | < ends up here still
```
The cycle doesn't end really, unless you ensure a method for example only ends one level beyond its own parent/root form. To illustrate the normal behavior for 1 level (4 spaces)

```python
def foo(bar):
     return "bam" # return here is
     # | cursor ends here
#| cursor ends up here
#| and stays here

```

I guess the solution might be that once an item is beyond 1st level and has a empty line following it, the consecutive forms should not be pushed further than original level they're at but this problem might be a bit harder (or easier) than I imagined, I figured some people here are a bit further than I am in the whole cursor/line based position game as I've barely touched that ground yet. But I do not think there is any reasonable way to determine if anything should with included or excluded from a previous form besides the fact that it should probably never cross boundaries? It might thus involve token checking that is in its infancy and I can't properly determine this... hence, post.

**Comment by cldwalker** [comment] 2015-02-20 16:29
Surprised the python plugin doesn't come configured with 4 spaces (given that's a community standard). Happy to take a pull request in Python plugin for that. :)

shift-tab for Python issue has also been observed in #1627. Since we get all language behaviors from CodeMirror, have you tried this case [against the Python demo](http://codemirror.net/mode/python/index.html)? If it's buggy there, then you should open this issue against CodeMirror. If it's not a bug there, then try updating [python.js](https://github.com/LightTable/Python/blob/master/codemirror/python.js) to the latest CodeMirror version. If that works then open a pull request or I can update python.js in the Python plugin

**Comment by talvdav** [comment] 2015-03-31 16:27
Hi,

if you press shift+enter the cursor will go to the root level again. But if you press enter again it will go to the last indent level.

Just testet it.
Hope this helps

o/

**Comment by clojens** [comment] 2015-04-05 00:52
Cheers. I haven't been using it much lately but I'll take you word for it and check next time.

**Comment by kenny-evitt** [comment] 2016-01-06 19:59
I'm closing this as it seems to be a duplicate of LightTable/Python#41 (which replaces #1627).

**Closed by kenny-evitt** 2016-01-06 19:59 UTC
Labels: python
