### ISSUE TITLE
Instarepl doesn't respect assertions / preconditions

### ISSUE THREAD

**Issue by mattmorten** [LightTable/LightTable#1824] opened 2015-01-20 00:11 UTC
The following code snippet, when evaluated manually using CMD-Enter (Mac), will throw an AssertionError:

```clojure
(defn do-something [a]
  {:pre [(= a 2)] :post []}
  a)

(do-something 5)
```

If I then choose "Make current editor an instarepl", Light table will evaluate the above code snippet to `5`.

Version 0.7.2 OS X Yosemite.

**Comment by cldwalker** [comment] 2015-01-20 04:46
This is a duplicate of #163. Any interest in looking into this is welcome

**Closed by cldwalker** 2015-01-20 04:46 UTC
