### ISSUE TITLE
unable to edit an rst file with Lighttable

### ISSUE THREAD

**Issue by carocad** [LightTable/LightTable#1909] opened 2015-05-19 17:25 UTC
I was trying to edit a README.rst file in Lighttable and found out that it makes it crash.
I get the following error on the console:
```
Uncaught TypeError: Cannot read property 'innerMode' of undefined
codemirror.js [4683]	CodeMirror.innerMode
codemirror.js [4124]	CodeMirror.getModeAt
codemirror.js [2458]	readInput
codemirror.js [2376]	p
```
This behavior can be easily replicated by simply creating an empty file test.rst file and try to edit it using Light Table.
After this error, any file that I open on Light table appears to be empty even though they aren't.
My environment is: 
* Ubuntu 14.04
* Light Table v0.7.2
* Binary version 0.8.6

**Comment by rundis** [comment] 2015-06-17 06:05
not able to reproduce (on Mac), anybody else with Ubuntu that has this problem ?

**Comment by kenny-evitt** [comment] 2015-06-17 13:52
I was able to reproduce this on Windows. Weird!

**Comment by dosmoc** [comment] 2015-06-24 16:08
I can't reproduce this in the atom-shell branch on Arch Linux, nor Windows 7.

**Comment by kenny-evitt** [comment] 2015-06-24 19:26
I couldn't reproduce this just now running the *atom-shell* branch on Windows 7. I think I must have been running the 0.7.2 version before.

**Comment by sashton** [comment] 2015-06-25 01:31
Can't reproduce:
- Ubuntu 64 bit 13.10
- atom-shell branch

**Comment by kenny-evitt** [comment] 2015-06-25 13:27
@carocad This seems like it might be resolved in the *atom-shell* branch version; would you try to reproduce this with that version?

**Comment by ShayMatasaro** [comment] 2015-07-15 20:35
no issue on 
 on ubuntu 14.04 
with master branch

**Comment by rundis** [comment] 2015-07-15 20:41
Ok. I'm closing this one. Nobody able to reproduce. @carocad Feel free to let me know if it turns out to still be a problem.

**Closed by rundis** 2015-07-15 20:41 UTC
Labels: bug, linux, windows
