### ISSUE TITLE
Watch selection dont work in JS

### ISSUE THREAD

**Issue by claudionebbia** [LightTable/LightTable#1912] opened 2015-06-01 16:41 UTC
In Windows 7, LightTable ##0.7.2, when I hit alt-w (Editor: Watch selection) whith a variable name selected, the console shows:

```
Invalid behavior: :lt.plugins.js/on-eval.one
TypeError: Cannot read property 'from' of undefined
    at lt.plugins.watches.watched_range (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:32584:270)
    at eval (C:%5CUsers%5CClaudio%5CDesktop%5CLightTable%5Cplugins%5Cjavascript%5Cjavascript_compiled.js:622:1846)
    at Function.__BEH__on_eval__DOT__one (C:%5CUsers%5CClaudio%5CDesktop%5CLightTable%5Cplugins%5Cjavascript%5Cjavascript_compiled.js:627:3)
    at c (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:20443:76)
    at a (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:20477:18)
    at a (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:20488:34)
    at b (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:20492:14)
    at Function.lt.plugins.watches.__BEH__eval_on_watch_or_unwatch (file:///C:/Users/Claudio/Desktop/LightTable/core/node_modules/lighttable/bootstrap.js:32648:26)
```

**Comment by rundis** [comment] 2015-06-17 06:02
Couldn't reproduce (on mac). Does this happen all the time ? Connected to internal or external browser ?

**Comment by kenny-evitt** [comment] 2015-06-17 13:44
@claudionebbia Please post a minimal example of code that exhibits this issue so we can try to reproduce it.

**Comment by cldwalker** [comment] 2015-08-29 20:44
Closing as we can't reproduce without a minimal example

**Closed by cldwalker** 2015-08-29 20:44 UTC
