### ISSUE TITLE
Saving HTML or JS files connected to browser doesn't refresh browser tab

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#2000] opened 2015-10-03 17:42 UTC
@cldwalker @rundis

I'm QA-ing the latest *master* version on my Linux box and one item I'm testing isn't working as I'm interpreting it as written in [the QA checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist):

> Save on a css, js and html file refreshes connected webpage

Is saving itself really supposed to be sufficient for the connected browser tab to refresh automatically? Or do I need to eval the files instead? Eval-ing works; saving doesn't.

**Comment by kenny-evitt** [comment] 2015-10-03 17:59
Huh; I see some errors logged in the console [I don't know if I just missed them before; that's very possible]:

```
Invalid behavior: :lt.plugins.html/eval-on-save
```

```
TypeError: Cannot read property 'call' of null
    at lt.object.has_tag_QMARK_ (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:18151:127)
    at lt.objs.clients.placeholder_QMARK_ (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:28874:35)
    at eval (/home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/plugins/HTML/html_compiled.js:27:68)
    at Function.__BEH__eval_on_save (/home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/plugins/HTML/html_compiled.js:31:3)
    at c (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6196:14)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at c (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17774:76)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17808:18)
    at a (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17819:34)
    at b (file:///home/kenny/@code/LightTable/builds/lighttable-0.8.0-alpha-linux/resources/app/core/node_modules/lighttable/bootstrap.js:17823:14)
```

**Comment by kenny-evitt** [comment] 2015-10-03 18:06
Actually, saving a CSS files *does* cause the browser tab to 'refresh' – really the CSS is just being re-evaluated. I can tell it's not being refreshed, in the usual sense of what that would mean, because the browser tab isn't showing changes I made, and saved, for the HTML file.

**Comment by kenny-evitt** [comment] 2015-10-03 18:13
This seems like it might be related to this:

 - [Error saving HTML connected to browser -> Invalid behavior: :lt.plugins.html/eval-on-save · Issue #1309 · LightTable/LightTable](https://github.com/LightTable/LightTable/issues/1309)

But I'm not getting those errors, the same ones I quoted above. I disconnected all of the connections. I closed the tabs for my HTML, CSS, and JS files. I re-opened the HTML file and eval-ed the entire file. Two connections were created; details from the connect bar:

```
file:///home/kenny/@code/LightTable/qa-examples/web.html
Type	:frame
Commands	
:editor.eval.cljs.exec
:editor.eval.css
:editor.eval.js
:editor.eval.html
```

and

```
file:///home/kenny/@code/LightTable/qa-examples/web.html
Type	:websocket
Commands	
:editor.eval.js
:editor.eval.cljs.exec
:editor.eval.html
:editor.eval.css
```

I opened the CSS file and eval-ed the whole file. I connected it to the first connection listed in the popup. If the order of connections matches what's shown in the connect bar, that would be type `:frame` connection.

I opened the JS file and eval-ed the whole file. The JS file just logs a string to the console. The console shows that string being logged twice – maybe because of the two connections?

Saving changes made to the CSS file cause the browser tab to 'refresh'. Saving changes to the HTML or JSS file does not affect the browser tab. Eval-ing the entire file for both the HTML and JS files *does* cause the browser tab to refresh.

**Comment by kenny-evitt** [comment] 2015-10-03 18:15
Bear with me – I'm mixing up things I've observed. I'm going to start over and describe the exact steps I take and the resulting behavior.

**Comment by kenny-evitt** [comment] 2015-10-03 18:31
I made [a separate repo with the example code I'm using to QA](https://github.com/kenny-evitt/LightTable-QA-examples).

**Comment by kenny-evitt** [comment] 2015-10-03 18:48
1. I removed [the LT WebSocket JS script from my main HTML file](https://github.com/kenny-evitt/LightTable-QA-examples/blob/master/web.html#L11). [I'm guessing that was the cause of the second connection being made I mentioned above.]
 2. I closed and re-opened LT.
 3. I opened my main HTML file.
 4. I eval-ed the entire HTML file. A browser tab opened with the web page.
 5. I made a change to the HTML file and saved it – the browser tab was not affected.
 6. I eval-ed the entire HTML file – the browser tab was refreshed.
 7. I made another change to the HTML file and saved it – this time the browser tab *was* refreshed.

Without making any other changes, or closing LT:

 1. I opened the JS file.
 2. I eval-ed the entire JS file. The `console.log` call was logged twice in the LT console.
 3. I made a change to the JS file and saved it – nothing was logged to the LT console.
 4. I eval-ed the entire JS file – the `console.log` call was logged *once* to the LT console.
 5. I made another change to the JS file and saved it – nothing was logged to the LT console.

Without making any other changes or closing LT:

 1. I opened the CSS file.
 2. I eval-ed the entire file.
 3. I made a change to the file and saved it – the browser tab reflected the change.

**Comment by kenny-evitt** [comment] 2015-10-04 14:12
I was able to reproduce the exact same behavior (as described in the previous comment) on my Mac OS X box.

**Comment by kenny-evitt** [comment] 2015-10-05 21:40
I was able to reproduce the exact same behavior on my Windows 7 computer.

**Comment by cldwalker** [comment] 2015-10-11 16:08
@kenny-evitt Thanks for looking into this. I confused save with eval for that item :disappointed:  and have updated the checklist. The save behavior is consistent with the behaviors in the plugin: [HTML save works once an eval client is set](https://github.com/LightTable/HTML/blob/1d1a736387732f3aef5fae8129be4028fb3f45af/src/lt/plugins/html.cljs#L26), [same for CSS](https://github.com/LightTable/CSS/blob/dc2b2b01609efb94b17993d40c04fb4a030f83e0/src/lt/plugins/css.cljs#L40) and JS has no on-save behavior which makes sense since it wouldn't be a sane default to re-eval the whole file. Feel free to open an new issue for [the above stacktrace](https://github.com/LightTable/LightTable/issues/2000#issuecomment-145272788) if it is reproducible. I didn't come across it in osx. The two prints/evals that occur an initial eval could be a minor bug. If you think so, please log it in the JavaScript repo. Otherwise, this issue is expected behavior and can be closed

**Comment by kenny-evitt** [comment] 2015-10-13 15:10
@cldwalker What about needing two evals for the on-save to work for HTML? I'll create a separate issue in the HTML plugin repo for that if it's not the expected behavior.

**Comment by cldwalker** [comment] 2015-10-13 16:04
@kenny-evitt I didn't need two evals for on-save to work on HTML on osx. I only needed one eval same as css. From the above links, I don't see a reason why it would differ from css. Perhaps a timing issue on Windows. Worth opening an issue on HTML repo if issue persists

**Comment by cldwalker** [comment] 2015-11-06 07:37
@kenny-evitt Closing as it's unclear there is still an issue. If there is, please open in the HTML repo with reproducible steps for Windows and two evals

**Closed by cldwalker** 2015-11-06 07:37 UTC
