### ISSUE TITLE
80-100% CPU usage all the time

### ISSUE THREAD

**Issue by valueof** [LightTable/LightTable#1088] opened 2014-01-13 23:46 UTC
My copy of LightTable seems to be constantly using 80-100% of my CPU and I have no idea why.

```
$ top -o cpu
Processes: 212 total, 2 running, 5 stuck, 205 sleeping, 1180 threads                                      15:44:59
Load Avg: 3.18, 8.62, 8.46  CPU usage: 15.72% user, 9.11% sys, 75.16% idle
SharedLibs: 18M resident, 11M data, 0B linkedit.
MemRegions: 67626 total, 3046M resident, 71M private, 1425M shared. PhysMem: 11G used (1994M wired), 4339M unused.
VM: 547G vsize, 1066M framework vsize, 3169146(0) swapins, 3504586(0) swapouts.
Networks: packets: 16954010/9810M in, 8503712/1823M out. Disks: 2046192/46G read, 3012196/111G written.

PID    COMMAND      %CPU  TIME     #TH   #WQ   #PORT #MREGS MEM    RPRVT  PURG   CMPRS  VPRVT  VSIZE  PGRP  PPID
48377- node-webkit  76.8  84:48.93 16    0     149   1363   458M-  457M-  0B     0B     1090M  1874M  48375 48375
...
```

I'm on OS X 10.9.1, reproduced both on my Air at home and Pro at work. I'll be happy to debug further—what information is helpful in this case?

**Comment by jdf-id-au** [comment] 2015-05-19 08:30
Is the nw problem [fixed now](https://github.com/nwjs/nw.js/issues/2723#issuecomment-103095335)? (Does LT use CSS3 animations?)

**Comment by JKGisMe** [comment] 2015-06-21 19:30
I downloaded & installed LT for the first time 2 days ago. Opened a file in it and got distracted. Never did anything else in LT. Today I am working in another app and suddenly my laptop fans start going like crazy. Turns out to be this node-webkit helper. I close light table and it takes about 3 minutes for the process to go away. 

I don't think I had any plugins unless there are any that run by default.

OSX 10.10.3

**Comment by kenny-evitt** [comment] 2015-06-21 19:46
@jdf-id-au @JKGisMe If you could, try building and running the *atom-shell* branch version.

**Comment by BenjaminVanRyseghem** [comment] 2015-07-01 22:52
I used to experienced something similar quite often.

Now that I am using the `atom-shell` branch, I will report it here if I bump into this again :smile:

**Comment by kenny-evitt** [comment] 2015-07-14 01:28
*atom-shell* is merged into *master*; just run a build of the latest source.

**Comment by Ghassan** [comment] 2015-08-10 22:53
I am running LT 0.7.2 on OSX 10.10.4 MBP 16 GB RAM and I get:
1) the user_compiled.js error which I don't know what it is. 
2) node-webkit Helper is choking the entire Mac. usually runs about 140% CPU time. 

I have to frequently restart sometimes my entire Mac.

**Comment by GetContented** [comment] 2015-08-11 01:58
This project hasn't had a commit for 26 days, sadly.

**Comment by kenny-evitt** [comment] 2015-08-11 15:04
@Ghassan Would you create a new issue for [1] and provide enough details for someone to reproduce the error you're observing?

But before you do that, please try building Light Table from the latest source of the *master* branch. The latest source version shouldn't have this issue as LT was migrated from node-webkit to Atom/Electron (precisely to fix this and other similar issues).

**Comment by kenny-evitt** [comment] 2015-08-11 15:05
@GetContented Pull requests welcome! And keep in mind that this project is spread out over multiple repos; most of the interesting functionality is implemented in separate plugins, and there has even been an update to one of them since the last commit for this repo.

There are a few of us working on packaging up the latest version as a new release, but we're not the original contributors so it's slow going for us to get up (and stay up) to speed on everything.

**Comment by GetContented** [comment] 2015-08-11 16:47
@kenny-evitt understood! It's hard to know this stuff as an "ordinary observer"... no blog updates for over 6 months, too. Would be good if there were slightly more frequent updates there. Not trying to be overly critical, just letting you know what it seems like. Anyway, this probably isn't the right spot to make this comment (not sure where is, though).

**Comment by kenny-evitt** [comment] 2015-08-11 20:43
@GetContented There's a few of us somewhat active on the [Gitter room](https://gitter.im/LightTable/LightTable) for this, the main GitHub repo. [The Google Groups group](https://groups.google.com/forum/#!forum/light-table-discussion) is also suitable for general questions and discussion.

**Comment by Ghassan** [comment] 2015-08-11 21:45
@kenny-evitt I downloaded the main branch, looked around everywhere possible for instructions on how to build LightTable from the source but couldn't find any. Went ahead and ran build.sh under script (don't know if this is all there is though?). then I executed "light" under builds which I noticed it was created after I ran the script. 

The editor opened had "About Atom" as the first menu item under LighTable menu, but does not respond to "^-space" to open the command menu and "View" menu doesn't have light table options. 

So I wasn't able to use the editor. I did notice the switch to Atom/Electron.

**Comment by kenny-evitt** [comment] 2015-08-11 21:54
@Ghassan Running `script/build-app.sh` is all you need to do to build – assuming you have Node.js and npm installed.

Instead of running `script/light.sh`, I usually run the build output executable directly; in your case the *LightTable.app* file under *builds\lighttable-0.8.0-mac*.

**Comment by Ghassan** [comment] 2015-08-11 22:05
I have node 0.12.7 and npm 2.12.1. Running build-app.sh doesn't do much. Just the same behavior. I tried to delete "builds" directory but it did not recompile. Any advice? also pointers to docs on how to build from source with optional commands? Thanks a lot.

**Comment by kenny-evitt** [comment] 2015-10-02 18:34
@Ghassan I was wrong in writing earlier that you only need to run `script/build-app.sh` – you need to run `script/build.sh` at least once. `build-app.sh` just packages the build files.

If you can, try building the latest source version again.

> also pointers to docs on how to build from source with optional commands?

I'm not sure what you mean by "optional commands".

**Comment by Ghassan** [comment] 2015-10-04 06:20
Ah, ok, thank you so much for letting me know. I'll try that.

-Ghassan
[image: www.linkedin.com/in/ghassanayesh]
<http://www.linkedin.com/in/ghassanayesh>
http://ghassan-ayesh.blogspot.com/

**Comment by kenny-evitt** [comment] 2015-11-15 20:08
@valueof @geoffrys @mynomoto @michaelphines @afhammad @otmezger @GetContented @davidssmith @mrobbetts @AlBaker @marcusps @pnutus @hamoid @icorderi @jdf-id-au @JKGisMe @Ghassan If you would, please confirm whether you're still having this problem with the 0.8.0-alpha version. That version includes the migration from node-webkit to Electron (Atom Shell).

**Comment by cldwalker** [comment] 2016-01-01 00:50
We've had 0.8.0 out for a month and haven't heard back. Closing until we have reproducible steps that can lead to a fix

**Closed by cldwalker** 2016-01-01 00:50 UTC

**Comment by GetContented** [comment] 2016-01-01 02:01
Not sure about others, or even if you want to know this, but I gave up using light table ages ago.

**Comment by davidssmith** [comment] 2016-01-01 03:36
@GetContented Me too.
