### ISSUE TITLE
Plugin manager not working

### ISSUE THREAD

**Issue by tharibo** [LightTable/LightTable#2010] opened 2015-10-07 11:36 UTC
Using LightTable 0.7.2 on Windows 7 Pro.

# Steps:

<C-space>plugin   --> Plugins: Show plugin manager
"Updating plugin metadata" turns for some seconds, then
"plugin install failed: metadata"

Showing the console:
```
Error: ENOENT, no such file or directory 'C:\Users\tharibo\AppData\Local\LightTable\metadata-temp'
    at Object.fs.readdirSync (fs.js:654:18)
    at lt.objs.files.full_path_ls (file:///D:/Users/tharibo/home/programs/LightTable/core/node_modules/lighttable/bootstrap.js:21917:134)
    at Extract.eval (file:///D:/Users/tharibo/home/programs/LightTable/core/node_modules/lighttable/bootstrap.js:29195:69)
    at Extract.EventEmitter.emit (events.js:117:20)
    at DirWriter.eval (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\lib\extract.js:66:8)
    at DirWriter.EventEmitter.emit (events.js:117:20)
    at end (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:323:12)
    at eval (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:313:32)
    at endUtimes (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:216:58)
    at setProps (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:296:5)
Error: ENOENT, no such file or directory 'C:\Users\tharibo\AppData\Local\LightTable\metadata-temp'
    at Object.fs.unlinkSync (fs.js:760:18)
    at lt.objs.files.delete_BANG_ (file:///D:/Users/tharibo/home/programs/LightTable/core/node_modules/lighttable/bootstrap.js:21835:131)
    at Extract.eval (file:///D:/Users/tharibo/home/programs/LightTable/core/node_modules/lighttable/bootstrap.js:29197:34)
    at Extract.EventEmitter.emit (events.js:117:20)
    at DirWriter.eval (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\lib\extract.js:66:8)
    at DirWriter.EventEmitter.emit (events.js:117:20)
    at end (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:323:12)
    at eval (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:313:32)
    at endUtimes (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:216:58)
    at setProps (D:\Users\tharibo\home\programs\LightTable\core\node_modules\tar\node_modules\fstream\lib\writer.js:296:5)
```

# Available plugins

No plugin is shown in the "available" tab.

# Proxy ?

I thought about some proxy issue, but i could report the issue by using Help/Report the issue, which opens the GitHub page in the internal browser.

**Comment by kenny-evitt** [comment] 2015-10-07 13:20
@tharibo I have no reason to believe this has been fixed but would you try reproducing this with the latest source version?

**Comment by tharibo** [comment] 2015-10-07 13:36
@kenny-evitt Sincerely, I wouldn't mind trying a new beta version, but Cygwin isn't installed on my system and I don't plan to do it soon. Would you be so kind as to provide a compiled version I can test?
Or did I miss some nightly-builds somewhere?

**Comment by kenny-evitt** [comment] 2015-10-07 14:21
The weird thing about the errors is that you seem to have LT installed under your Windows *Users* directory on your *D* drive but LT is looking for the plugin data in a path on your *C* drive.

Would you check the environment variable *APPDATA* and let me know what its value is?

[Here's a build of a very recent source version.](https://www.dropbox.com/s/82q1kbrq92iui3q/lighttable-0.8.0-alpha-windows.zip?dl=0)

**Comment by tharibo** [comment] 2015-10-07 14:51
As a matter of fact, I really have a D:/users/tharibo directory AND a C:users/tharibo directory. The C one is the windows user directory, the D one is my DATA directory.
Since LightTable is provided as a ZIP and I prefer to keep my personal utilities programs, I have a D:users/tharibo/home/programs directory where I have portable versions of different utilities.

Anyway, I tested the case: copied LightTable directory to C:/ and retried from there: same problem.
I tried to remove the APPDATA/LightTable directory too.

%APPDATA%: C:\Users\tharibo\AppData\Roaming

With the very recent source version, the error message doesn't show up, but metadata update doesn't stop (infinite loop or no timeout...). In the Available tab, nothing shows up. Typing "vim" for example does nothing more.

New error message:
```
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:51:11)
    at Object.exports.request (http.js:31:10)
    at TunnelingAgent.exports.request (https.js:163:15)
    at TunnelingAgent.createSocket (D:\Users\tharibo\home\programs\lighttable-0.8.0-alpha-windows\resources\app\core\node_modules\request\tunnel.js:117:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (D:\Users\tharibo\home\programs\lighttable-0.8.0-alpha-windows\resources\app\core\node_modules\request\tunnel.js:184:41)
    at TunnelingAgent.addRequest (D:\Users\tharibo\home\programs\lighttable-0.8.0-alpha-windows\resources\app\core\node_modules\request\tunnel.js:80:8)
    at new ClientRequest (_http_client.js:133:16)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (D:\Users\tharibo\home\programs\lighttable-0.8.0-alpha-windows\resources\app\core\node_modules\request\main.js:559:30)
```

**Comment by cldwalker** [comment] 2015-11-06 07:44
Can you try 0.8.0-alpha - available for download off the website.

> I thought about some proxy issue, but i could report the issue by using Help/Report the issue, which opens the GitHub page in the internal browser.

Could you clarify what this means? Are you behind a proxy? If so that is why you're having trouble because we don't have proxy support yet - see #1984. If you aren't behind a proxy, there isn't enough information here to reproduce and fix this bug

**Comment by tharibo** [comment] 2015-11-09 07:38
Hi.

Yes I am behind a proxy. Seeing #1984 I thought I had nothing to do. When I ping a server using command line, it works no question asked. Our proxy uses our Windows credentials transparently.
I'll try the 0.8.0-alpha anyway.

**Comment by kenny-evitt** [comment] 2015-11-16 22:50
@tharibo @cldwalker I'm closing this as this should be covered by #1984.

**Closed by kenny-evitt** 2015-11-16 22:50 UTC
Labels: not-reproducible, windows

**Comment by howardlinus** [comment] 2016-04-19 15:14
I have the following error when turn on Plugin Manager

console output:
Error: ENOENT: no such file or directory, scandir 'C:\Users\userid\AppData\Roaming\LightTable\metadata-temp'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:454:28)
    at lt.objs.files.full_path_ls (file:///C:/Users/userid/Documents/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21849:134)
    at Extract.<anonymous> (file:///C:/Users/userid/Documents/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:29218:69)
    at emitNone (events.js:72:20)
    at Extract.emit (events.js:166:7)
    at DirWriter.<anonymous> (C:\Users\userid\Documents\lighttable-0.8.1-windows\resources\app\core\node_modules\tar\lib\extract.js:66:8)
    at emitNone (events.js:72:20)
    at DirWriter.emit (events.js:166:7)
Error: ENOENT: no such file or directory, unlink 'C:\Users\userid\AppData\Roaming\LightTable\metadata-temp'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:947:18)
    at lt.objs.files.delete_BANG_ (file:///C:/Users/userid/Documents/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:21783:131)
    at Extract.<anonymous> (file:///C:/Users/userid/Documents/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:29220:34)
    at emitNone (events.js:72:20)
    at Extract.emit (events.js:166:7)
    at DirWriter.<anonymous> (C:\Users\userid\Documents\lighttable-0.8.1-windows\resources\app\core\node_modules\tar\lib\extract.js:66:8)
    at emitNone (events.js:72:20)
    at DirWriter.emit (events.js:166:7)
    at end (C:\Users\userid\Documents\lighttable-0.8.1-windows\resources\app\core\node_modules\tar\node_modules\fstream\lib\writer.js:323:12)

**Comment by kenny-evitt** [comment] 2016-04-22 01:42
@howardlinus That doesn't look like a proxy error. Would you create a new issue for that error and provide all [the info we request when reporting bugs](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs) when you do so?

**Comment by kenny-evitt** [comment] 2016-04-22 01:44
@howardlinus Sorry – I didn't reread the previous comments before my last comment. Are you behind a proxy?

**Comment by mluisbrown** [comment] 2016-05-10 22:24
@kenny-evitt and @howardlinus see my comment on #1984. I believe this is a proxy problem. I think that the proxy is preventing the `metadata_temp.tar.gz` file from being correctly downloaded, so the expansion doesn't work, resulting in the missing directory.

**Comment by NoWayHoze** [comment] 2016-12-14 06:51
This might not be the case here, but my lighttable folder was read only mode in windows 10.
