### ISSUE TITLE
Instarepl doesnt work

### ISSUE THREAD

**Issue by sunlchk** [LightTable/LightTable#2283] opened 2016-10-06 05:32 UTC
## _Instarepl doesnt work_

When i opened lighttable it asked for upgrade and then it asked for plugin upgrade

Now instarepl is not available.i tried downloading latest version it would not work

I reverted to old version but still unable to see intarepl.

Could you please let me know on this

**Comment by rundis** [comment] 2016-10-06 05:56
Sorry to hear that.

1. What version of Light Table were you using before the upgrade ? If it was prior to 0.8 the upgrade procedure doesn't work unfortunately. It was a major upgrade of the core architectural components in Light Table with 0.8. Bottom line here is to use the latest version of Light Table (0.8.1), you should try download and install from lighttable.com. Then try to install the instarepl plugin from the plugin manager.

2. With version 0.8 of Light Table we decided to deprecate support for the instarepl and stop bundling it with the distribution. Partially to scope down what we need to support and partially because none of us were using it. The instarepl plugin will not be supported from the Light Table team from once 0.9  of LT is released. 
The instarepl was a cool idea, but it also had quite a few problems and introduced a whole range of support request we simply don't currently have the bandwidth to handle. 


Having said all this, the instarepl should still work and be possible to use. But it does have quite a few known issues that are unlikely to be addressed unless someone wants to take over maintenance of the plugin: https://github.com/LightTable/ClojureInstarepl

3. The obvious, but not quite as fancy workaround is to use manual eval (ctrl/cmd-enter) in your clojure/clojurescript files.

**Comment by Mouvedia** [comment] 2016-10-06 22:17
dupe of #2163?

**Comment by sbauer322** [comment] 2016-10-10 04:23
We should also make note of the intention to deprecate on ClojureInstarepl's README in the event a maintainer is not found.

**Comment by pate** [comment] 2016-10-18 18:20
Same thing happened to me. Installing the plugin "ClojureInstarepl" restores the feature:

![image](https://cloud.githubusercontent.com/assets/1011676/19490639/3efc88c6-9570-11e6-8ab0-4c024bb74bf3.png)

**Comment by pate** [comment] 2016-10-18 18:21
@sbauer322, does this mean instarepl is going away? I love the instarepl for teaching Clojure, and use it for prototyping.

**Comment by rundis** [comment] 2016-10-18 19:24
@pate it means it will die eventually if no one voluenteers to pick it up and maintain it. A bit sad tbh, but the core team just doesn't  have the capacity (and sufficient motivation as none of us use it ) to keep it in shape and someone from the community needs to step up.

**Comment by rundis** [comment] 2016-10-31 19:46
@sunlchk Did you manage to get instarepl to work ? If not please open a new issue in the instarepl repository https://github.com/LightTable/ClojureInstarepl

**Closed by rundis** 2016-10-31 19:46 UTC
