### ISSUE TITLE
Clojure Instarepl loops endlessly

### ISSUE THREAD

**Issue by chetanns** [LightTable/LightTable#1873] opened 2015-03-12 00:28 UTC
While loading the instarepl first time. The instarepl is not getting connected. In the bottom status the connecting sign keeps showing for endless amount of time. No errors whatsoever is shown.

I am facing issue in the windows environment. Due to this, i am not able to run ,my clojure code in light table.

**Comment by kenny-evitt** [comment] 2015-03-20 13:30
@chetanns are you able to load a Leiningen REPL for a new project on your computer?

**Comment by chetanns** [comment] 2015-03-20 22:06
Yes, from outside the Lighttable. I am able to run the Leiningen REPL for a new project.

**Comment by kenny-evitt** [comment] 2015-03-25 13:22
Would you share a minimal project for which you can reproduce this issue? I'll try to reproduce it myself.

What versions of Windows and Light Table are you running?

**Comment by acron0** [comment] 2015-03-25 13:47
Could it be related to https://github.com/LightTable/LightTable/issues/1848?

**Comment by kenny-evitt** [comment] 2015-03-26 13:43
@acron0 this is definitely different; @chetanns reported "no errors". It's possibly the same, or a similar, underlying issue.

**Comment by acron0** [comment] 2015-03-26 13:50
I only say that because I experience both these issues, but sometimes I get an error and sometimes I don't... :+1:

**Comment by chetanns** [comment] 2015-03-27 01:00
Hi
I have attached the screenshot of the lighttable screen, where i am trying to load the instarepl.

Kindly note the following thing in the screenshot

1> The red block showing the status icon. This does not change and stays that way forever.
2> When i opened the task manager, I noticed that 3 instance of lighttable are running along with 2 instance of java. Is this the expected behaviour.

As requested, I have created a simple lein project from the command prompt. It has only one file and just prints the "Hello World". But I am not able upload the project. Kindly let me know a way to share that project.

The lighttable 0.7.4 is installed on windows 7 64 bit version.
![screenshot](https://cloud.githubusercontent.com/assets/11432586/6860157/bfd85cec-d3fa-11e4-92b3-8c7142f33b79.jpg)

**Comment by kenny-evitt** [comment] 2015-03-27 14:13
@chetanns if you close Light Table, how many Light Table processes are still listed in Task Manager?

I just opened Light Table on my computer, opened a new Clojure InstaREPL, and Task Manager only lists two "Light Table" processes.

Try closing Light Table and then killing any remaining "Light Table" processes listed in Task Manager.

**Comment by chetanns** [comment] 2015-03-29 18:27
If i close the LightTable, I do not see any LightTable processes in the TaskManager.

**Comment by kenny-evitt** [comment] 2015-03-30 13:54
@chetanns have you tried entering some code in the InstaREPL tab? I vaguely remember the 'spinner' animation never stopping for me before but I was still able to run code.

**Comment by chetanns** [comment] 2015-03-31 01:33
Yes, I tried running the code in the InstaRepl tab. Still no response and the spinner animation never stops.

**Comment by kenny-evitt** [comment] 2015-04-06 13:45
@chetanns would you paste the contents of your *project.clj* file for the simple Leiningen project you created to reproduce this? I didn't think of it before, but you could create a public repo in GitHub for the sample project as a way to share it. But I think the *project.clj* file contents should be enough.

Also, what version of Clojure do you have installed? [Run `(clojure-version)` from a Leiningen REPL.]

**Comment by kenny-evitt** [comment] 2015-04-07 20:00
@chetanns would you also, while Light Table is running, and after you've opened a new Clojure InstaREPL tab, check the file *C:\Users\...\AppData\Local\LightTable\plugins\Clojure\window0.log*? It may contain useful info pertaining to whatever is wrong with the LT REPL.

**Comment by chetanns** [comment] 2015-04-08 00:59
In the C:\Users...\AppData\Local\LightTable\plugins\, I did not find any clojure  folder.

**Comment by chetanns** [comment] 2015-04-08 01:01
And below is the contents of my project.clj file

(defproject command-line-args "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]]
  :profiles {:dev {:plugins [[cider/cider-nrepl "0.7.0"]]}})

**Comment by acron0** [comment] 2015-04-08 07:37
I don't have a Clojure folder in plugins either

**Comment by acron0** [comment] 2015-04-08 07:43
I found the file in /logs rather than /plugins

    STARTING CLIENT: java -jar D:\Applications\LightTable\plugins\clojure\runner\target\lein-light-standalone.jar LightTable-REPL[stdout]: final project:  {:compile-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name LightTable-REPL, :project (quote {:compile-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values]}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.2.0] [im.chit/hara.class 2.1.8] [im.chit/hara.reflect 2.1.8]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path D:\Applications\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root D:\Applications\LightTable\plugins\clojure\runner\resources, :offline? false, :source-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\dev-resources D:\Applications\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([lein-bin/lein-bin 0.3.4] [venantius/ultra 0.2.0]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]})})}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.1.0] [org.clojure/tools.reader 0.8.3] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.2.0] [im.chit/hara.class 2.1.8] [im.chit/hara.reflect 2.1.8]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path D:\Applications\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root D:\Applications\LightTable\plugins\clojure\runner\resources, :offline? false, :source-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\dev-resources D:\Applications\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([lein-bin/lein-bin 0.3.4] [venantius/ultra 0.2.0]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]}
    [stderr]: Exception in thread "main" [stderr]: java.lang.ClassNotFoundException: lighttable.nrepl.core, compiling:(C:\Users\Antony\AppData\Local\Temp\form-init7648435000456649766.clj:1:1047)
	at clojure.lang.Compiler.analyze(Compiler.java:6380)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
    [stderr]: 	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.eval(Compiler.java:6616)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
    [stderr]: 	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
    [stderr]: 	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
    [stderr]: Caused by: java.lang.ClassNotFoundException: lighttable.nrepl.core
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2070)
	at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:969)
	at clojure.lang.Compiler$HostExpr.access$400(Compiler.java:747)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6766)
	at clojure.lang.Compiler.analyze(Compiler.java:6343)
	... 25 more
    [stderr]: clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 1}
    [stderr]: 	at clojure.core$ex_info.invoke(core.clj:4327)
	at leiningen.core.eval$fn__3532.invoke(eval.clj:226)
	at clojure.lang.MultiFn.invoke(MultiFn.java:231)
	at leiningen.core.eval$eval_in_project.invoke(eval.clj:326)
	at clojure.lang.AFn.applyToHelper(AFn.java:167)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:619)
	at leiningen.repl$repl.doInvoke(repl.clj:261)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at leiningen.light_nrepl$light.doInvoke(light_nrepl.clj:56)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at leiningen.light_nrepl$_main.doInvoke(light_nrepl.clj:68)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at leiningen.light_nrepl.main(Unknown Source)
    STARTING CLIENT: java -jar D:\Applications\LightTable\plugins\clojure\runner\target\lein-light-standalone.jar LightTable-REPL[stdout]: final project:  {:compile-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name LightTable-REPL, :project (quote {:compile-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :ultra {:color-scheme :solarized_dark}, :repl-options {:nrepl-context {:interactive-eval {:renderer whidbey.render/render-str}}, :nrepl-middleware [clojure.tools.nrepl.middleware.render-values/render-values]}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.2.0] [im.chit/hara.class 2.1.8] [im.chit/hara.reflect 2.1.8]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path D:\Applications\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root D:\Applications\LightTable\plugins\clojure\runner\resources, :offline? false, :source-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\dev-resources D:\Applications\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([lein-bin/lein-bin 0.3.4] [venantius/ultra 0.2.0]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]})})}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.1.0] [org.clojure/tools.reader 0.8.3] [mvxcvi/puget 0.6.6] [mvxcvi/whidbey 0.4.2] [venantius/ultra 0.2.0] [im.chit/hara.class 2.1.8] [im.chit/hara.reflect 2.1.8]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path D:\Applications\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root D:\Applications\LightTable\plugins\clojure\runner\resources, :offline? false, :source-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\dev-resources D:\Applications\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins ([lein-bin/lein-bin 0.3.4] [venantius/ultra 0.2.0]), :injections ((clojure.core/require (quote ultra.hardcore)) (ultra.hardcore/configure! {:sort-keys true, :map-delimiter , :print-meta false, :color-scheme :solarized_dark})), :native-path D:\Applications\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (D:\Applications\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]}
    [stderr]: Exception in thread "main" [stderr]: java.lang.ClassNotFoundException: lighttable.nrepl.core, compiling:(C:\Users\Antony\AppData\Local\Temp\form-init9183633611497989374.clj:1:1047)
    [stderr]: 	at clojure.lang.Compiler.analyze(Compiler.java:6380)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
    [stderr]: 	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3624)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6562)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.analyze(Compiler.java:6322)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5708)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5139)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3751)
    [stderr]: 	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6558)
	at clojure.lang.Compiler.analyze(Compiler.java:6361)
	at clojure.lang.Compiler.eval(Compiler.java:6616)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.eval(Compiler.java:6608)
	at clojure.lang.Compiler.load(Compiler.java:7064)
    [stderr]: 	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
    [stderr]: 	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
    [stderr]: Caused by: java.lang.ClassNotFoundException: lighttable.nrepl.core
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
    [stderr]: 	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:61)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at clojure.lang.RT.classForName(RT.java:2070)
	at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:969)
    [stderr]: 	at clojure.lang.Compiler$HostExpr.access$400(Compiler.java:747)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6766)
	at clojure.lang.Compiler.analyze(Compiler.java:6343)
	... 25 more

**Comment by kenny-evitt** [comment] 2015-04-09 14:15
@acron0 thanks! Based on the log, you definitely seem to having the same issue as described in #1848. Would you share your *project.clj* file contents? Or create a public GitHub repo for a minimal project for which you can reproduce this?

**Comment by kenny-evitt** [comment] 2015-04-09 14:25
@chetanns I can't reproduce this with a new project with the same contents as the *project.clj* you posted. I thought maybe the CIDER nREPL plugin might have been causing the problem, but it doesn't seem to be doing so for me at least.

I mis-typed previously – would you check the *C:\Users...\AppData\Local\LightTable\logs* directory and add the contents of the *window0.log* file in it as a comment?

**Comment by chetanns** [comment] 2015-04-10 01:13
The below are the contents of the log file mentioned in the location.

STARTING CLIENT: java -jar E:\Development\Editor\LightTable\plugins\clojure\runner\target\lein-light-standalone.jar LightTable-REPL[stdout]: final project:  {:compile-path E:\Development\Editor\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :repl-options {:nrepl-middleware [lighttable.nrepl.handler/lighttable-ops], :init (clojure.core/swap! lighttable.nrepl.core/my-settings clojure.core/merge {:name LightTable-REPL, :project (quote {:compile-path E:\Development\Editor\LightTable\plugins\clojure\runner\resources\target\classes, :group local-client, :global-vars {}, :checkout-deps-shares [:source-paths :test-paths :resource-paths :compile-path #'leiningen.core.classpath/checkout-deps-paths], :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path E:\Development\Editor\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root E:\Development\Editor\LightTable\plugins\clojure\runner\resources, :java-cmd C:\Program Files\Java\jdk1.7.0_60\bin\java.exe, :offline? false, :source-paths (E:\Development\Editor\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (E:\Development\Editor\LightTable\plugins\clojure\runner\resources\dev-resources E:\Development\Editor\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins [], :native-path E:\Development\Editor\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (E:\Development\Editor\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]})})}, :dependencies ([org.clojure/clojure 1.5.1] [org.clojure/tools.nrepl 0.2.3 :exclusions ([org.clojure/clojure])] [clojure-complete/clojure-complete 0.2.3 :exclusions ([org.clojure/clojure])] [lein-light-nrepl/lein-light-nrepl 0.1.0] [org.clojure/tools.reader 0.8.3]), :plugin-repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :test-selectors {:default (constantly true)}, :target-path E:\Development\Editor\LightTable\plugins\clojure\runner\resources\target, :name local-client, :deploy-repositories [[clojars {:username :gpg, :url https://clojars.org/repo/, :password :gpg}]], :root E:\Development\Editor\LightTable\plugins\clojure\runner\resources, :java-cmd C:\Program Files\Java\jdk1.7.0_60\bin\java.exe, :offline? false, :source-paths (E:\Development\Editor\LightTable\plugins\clojure\runner\resources\src), :certificates [clojars.pem], :version 0.0.1, :jar-exclusions [#"^\."], :prep-tasks [javac compile], :repositories [[central {:snapshots false, :url http://repo1.maven.org/maven2/}] [clojars {:url https://clojars.org/repo/}]], :resource-paths (E:\Development\Editor\LightTable\plugins\clojure\runner\resources\dev-resources E:\Development\Editor\LightTable\plugins\clojure\runner\resources\resources), :uberjar-exclusions [#"(?i)^META-INF/[^/]*\.(SF|RSA|DSA)$"], :jvm-opts [], :eval-in :subprocess, :plugins [], :native-path E:\Development\Editor\LightTable\plugins\clojure\runner\resources\target\native, :description A local light table project, :uberjar-merge-with {META-INF/plexus/components.xml leiningen.uberjar/components-merger, data_readers.clj leiningen.uberjar/clj-map-merger}, :test-paths (E:\Development\Editor\LightTable\plugins\clojure\runner\resources\test), :clean-targets [:target-path]}
[stdout]: nREPL server started on port 1954 on host 127.0.0.1

**Comment by acron0** [comment] 2015-04-14 12:49
@kenny-evitt I shared my project.clj in https://github.com/LightTable/LightTable/issues/1848

**Comment by kenny-evitt** [comment] 2015-04-16 13:55
@chetanns, @acron0 thanks for the additional info. I was still unable to either reproduce this, or to find any likely candidates for what might be causing it.

However, I did come across [another issue](https://github.com/LightTable/LightTable/issues/1717) that seems very similar (if not exactly the same) to this one.

Would you both check what version of Java or the JDK you have installed?

**Comment by acron0** [comment] 2015-04-16 14:11
λ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode, sharing)

**Comment by kenny-evitt** [comment] 2015-04-16 14:18
@acron0 thanks. I can't tell if your version is earlier or later [than what was reported in that other issue as resolving that issue](https://github.com/LightTable/LightTable/issues/1717#issuecomment-93640958), but, if you can, please upgrade Java to try to resolve this.

**Comment by kenny-evitt** [comment] 2015-04-16 14:18
@acron0 are you running the 32-bit or 64-bit version of Java? I can't tell from the version info you posted.

**Comment by acron0** [comment] 2015-04-16 14:30
I tried upgrading to Java 8/45 64-bit

    λ java -version
    java version "1.8.0_45"
    Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Still the same error message...

**Comment by kenny-evitt** [comment] 2015-04-16 18:57
@acron0 bummer. I'm not sure what to try next. If I could reproduce it myself, I'd start adding debugging statements to the code to narrow it down to specific code. If you can build the Light Table Clojure/ClojureScript code on your computer, for both Light Table and the Clojure language plugin, you might be able to do that. I'm not really familiar with the Light Table code, but I'm glad to help you as much as I can.

...

I just read [this comment](https://github.com/LightTable/LightTable/issues/1848#issuecomment-72405415) on the issue you mentioned earlier and that comments references #1832, which concerns missing JAR files when building Light Table locally. Based on the contents of your log file, that seems to be the issue you're having.

@chetanns based on the log file you posted, Light Table *is* able to connect to an nREPL so it seems likely to be caused by something else. Are you building Light Table locally?

**Comment by acron0** [comment] 2015-04-17 08:11
@kenny-evitt The suggested fix in https://github.com/LightTable/LightTable/issues/1848 worked for me. Thanks for your assistance :)

**Comment by kenny-evitt** [comment] 2015-04-17 13:34
@acron0 awesome!

**Comment by martinchooooooo** [comment] 2015-04-23 17:56
Hey guys, 

Going through issues and it seems like this one is resolved. If it is, could someone please close it?

Cheers!

**Closed** 2015-05-20 15:21 UTC
Labels: windows
