### ISSUE TITLE
Markdown syntax highlighting doesn't support 'fenced' code blocks

### ISSUE THREAD

**Issue by Joshfindit** [LightTable/LightTable#1922] opened 2015-06-18 18:01 UTC
When typing in Markdown, the following are valid:
```js
    ```javascript
    var firstName = "Gregg";
    ```
```

``` clojure
    ``` clojure
    user=> (type #'user/my-number)
    clojure.lang.Var
    user=> ;
    ```
```
and
```js
    <script>
      var firstName = "Gregg";
      // This is less "valid", but works in Markdown compilers like Jekyll
    </script>
```

Currently, Light Table will highlight and format all code blocks as plain Markdown.

**Comment by kenny-evitt** [comment] 2015-06-18 18:46
Light Table uses [CodeMirror](http://codemirror.net/) for this. We're using version 4.7.0; the newest version is 5.3.0. [But even the newest version doesn't seem to support highlighting code blocks.](http://codemirror.net/mode/markdown/)

For regular Markdown you need to indent every line of the code block 4 spaces; this works:

        This is a code block and it's formatted as such in Light Table.

This syntax:

    ```
    code
    ```

is GitHub flavored Markdown and [(at least the newest version of) CodeMirror does support it](http://codemirror.net/mode/gfm/index.html)

Unfortunately, [Light Table doesn't register a file extension for GitHub-flavored Markdown](https://github.com/LightTable/LightTable/blob/20681a35258a95632e4c099d003399b98f5cb4ea/deploy/settings/default/default.behaviors#L294-L295). That line isn't in my default behaviors file locally by the way. Also, adding it to my user behaviors or default behaviors files, with an extension (that's not used by another type), doesn't enable syntax highlighting.

I'm stumped on how to get this to work.

**Comment by Joshfindit** [comment] 2015-06-19 02:03
Since you're stumped, maybe brainstorming will help.
Granted I'm very much an monkey poking at an interesting thing with a stick, so these suggestions may not even be feasible:

Is it possible to send just the code block to CodeMirror, then fold the result back in to the editor window?

Failing that, would Mixed Mode highlighting be an option?

**Comment by kenny-evitt** [comment] 2015-06-19 13:19
CodeMirror already 'has' the block – it's used for every editor tab in Light Table.

It doesn't seem like CodeMirror has 'mixed mode' highlighting.

**Comment by kenny-evitt** [comment] 2015-06-30 13:01
This is a duplicate of #1262. @Joshfindit – use that older issue for this please.

**Closed by kenny-evitt** 2015-06-30 13:01 UTC
