### ISSUE TITLE
Closing Browser tap causes other browsers tabs to refresh their content and lost work

### ISSUE THREAD

**Issue by cneira** [LightTable/LightTable#1820] opened 2015-01-14 22:21 UTC
When having multiple browser tabs, closing one causes the other to refresh and lost current input done on them.

OS : Windows 7 x64
Lightable:  0.7.2
Binary Version : 0.8.4

How to reproduce:

Just open multiple browser tabs for example, create one tab and load grooveshark select a couple of tracks, then start closing the rest of the browser tabs, then your current  groover session will be lost.

**Comment by cldwalker** [comment] 2015-11-06 08:11
Since grooveshark isn't around anymore, is there another way to reproduce this? On 0.8.0-alpha, I don't see items being lost in http://todomvc.com/examples/backbone/ if I open and close multiple tabs

**Comment by cldwalker** [comment] 2015-12-05 17:43
Closing as this isn't reproducible. Happy to reopen if we get reproducible steps

**Closed by cldwalker** 2015-12-05 17:43 UTC
Labels: not-reproducible
