### ISSUE TITLE
Fonts not rendering

### ISSUE THREAD

**Issue by burningraven06** [LightTable/LightTable#2367] opened 2018-04-17 11:38 UTC
Hello, 

Fonts are not rendering in the dialogue box / file browser, when I click "Open File" or "Open Folder" in Lighthouse.

Here is the screeshot. I am using Fedora 27.
Please let me know how to fix this.
Thank you.

![lighhttable](https://user-images.githubusercontent.com/18212542/38867509-c7349dfc-4233-11e8-83b6-bfb90b4a343f.png)

**Comment by Mouvedia** [comment] 2018-04-17 23:57
Are you getting #436 in your console?

**Comment by burningraven06** [comment] 2018-04-18 17:15
no, I'm seeing nothing in the console. I'm using LightTable v 0.8.1, and after extracting the tarball, I cd into the extracted folder and run the executable from the shell/terminal, LightTable starts up but nothing else appears in the console.

**Comment by sbauer322** [comment] 2018-04-18 18:03
Sounds a lot like https://github.com/LightTable/LightTable/issues/2360, which is related to https://github.com/LightTable/LightTable/pull/2359 and https://github.com/LightTable/LightTable/issues/2343

**Comment by Mouvedia** [comment] 2018-04-18 18:45
This should be closed as duplicate of #2343.
cf https://github.com/LightTable/LightTable/issues/2343#issuecomment-316613517

**Comment by sbauer322** [comment] 2018-04-19 01:06
Thank you for submitting the issue, @burningraven06. I am going to closing this issue as a duplicate of #2343 as it has the most activity.

**Closed by sbauer322** 2018-04-19 01:06 UTC
