### ISSUE TITLE
Typographic issues

### ISSUE THREAD

**Issue by autotel** [LightTable/LightTable#2490] opened 2020-05-25 08:12 UTC
I was trying LightTable, but did not work for me, I figured I could be a bit helpful before removing it.
Typographies are displayed with two different kinds of issues.

**Branch**
stable, last release
**To Reproduce**
Kubuntu 18.04, Kde plasma version 5.12.9

**Screenshots**
This is how the main interface looks like:
![image](https://user-images.githubusercontent.com/15053243/82792468-227b6e00-9e78-11ea-86fa-ccd74c210ff9.png)
* Minor typography glitches everywhere. If I report issue, it opens github page and interestingly the issues appear also there.

This is what the "open file" interface looks like:

![image](https://user-images.githubusercontent.com/15053243/82792564-42129680-9e78-11ea-8bee-352d24a1859e.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 18.04, plasma 5.12.9
 - Version 0.8.1, binary 0.34.5

**Comment by OrdoFlammae** [comment] 2020-05-25 16:40
Duplicate of #2343

**Comment by Mouvedia** [comment] 2020-05-25 17:23
dupe of #2368 and #2343

**Closed as completed by Mouvedia** 2020-05-25 17:23 UTC
Labels: resolution: duplicate
