### ISSUE TITLE
Bad encoding and fonts

### ISSUE THREAD

**Issue by sgchris** [LightTable/LightTable#2386] opened 2019-01-01 10:05 UTC
Hi,

I wanted to try the editor, but out of the box behavior seems to be bad. I have downloaded the tar.gz file from the website, and just executed the binary file.

My system:
```bash
greg@greg-home-desktop:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

![image](https://user-images.githubusercontent.com/475849/50571857-de885480-0dbc-11e9-8c2d-a7fada5e42c5.png)

There's no option to do some basic operations like opening a file or a folder. The editor becomes useless in this case. 

Additionally, the fonts look bad. Let me know if you need some additional information.

Thanks

**Comment by MarcusE1W** [comment] 2019-01-22 23:31
Unfortunately an older issue #2343

**Comment by myvdesk** [comment] 2019-02-07 05:11
not an issue, this guy fixed your problem with lighttable. https://github.com/ArchI3Chris/LightTable-Square-Fix

**Comment by Mouvedia** [comment] 2019-02-10 07:24
dupe of #2343

**Closed by Mouvedia** 2019-02-10 07:24 UTC
Labels: resolution: duplicate
