### ISSUE TITLE
windows 8.1pro 64b: context-menu/r-click "Open with" light table gens failed open

### ISSUE THREAD

**Issue by Brrrknee** [LightTable/LightTable#2036] opened 2015-11-06 06:15 UTC
I am only able to first open LT, then from the file menu open a file; when I attempt to open a file I'd associated with LT ( erlang *.erl in this case) by just double-click or r-click/open-with, LT never opens the file, but reflects these errors in the LT console:

```
Invalid behavior: :lt.objs.cli/open!
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:116:15)
    at lt.objs.files.resolve (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:21718:30)
    at eval (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:30444:38)
    at eval (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:7612:44)
    at cljs.core.LazySeq.sval (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:5561:40)
    at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:5571:8)
    at cljs.core._seq (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:2311:14)
    at cljs.core.seq (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:2824:27)
    at cljs.core.some (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:6382:23)
    at Function.lt.objs.cli.__BEH__open_BANG_ (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:30446:177)
```

This is just the normal double-click "open" in the windows domain.  
Neither does the normal windows "drag and drop" of file(s) onto the LT window work to open files -it should but I'd be happy to see it just open a file as any other program does in windows.

**Comment by kenny-evitt** [comment] 2015-11-06 12:51
Drag & drop only seems to work, on Linux at least, if there's already a tab open. Does that work for you?

I don't have access to a Windows 8 computer but I'll try to reproduce this on one of my Windows 7 computers.

**Comment by Brrrknee** [comment] 2015-11-06 15:10
No, d&d doesn't work with a tab open either.
BB


Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by kenny-evitt** [comment] 2015-11-07 20:11
@Brrrknee No errors or warnings logged to the LT console? Or in the logs [under the *LightTable/logs* user data sub-directory ]? There might also be messages written in a Command Prompt window if you run LT from it.

It might also be worth trying to do the same things with [the Atom editor](https://github.com/atom/atom/releases/tag/v1.1.0) so we can better determine if this is a problem on Windows 8 with LT or Electron, the app framework both LT and Atom run on.

**Comment by Brrrknee** [comment] 2015-11-08 02:10
Thought I’d explained in original, double-clicking an erl file associated to LT, this is generated in a new LT window: (an existing open LT is not seen/used)

·       Invalid behavior: :lt.objs.cli/open-on-args

·       TypeError: Arguments to path.resolve must be strings

·           at Object.exports.resolve (path.js:116:15)

·           at lt.objs.files.resolve (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:21718:30)

·           at eval (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:30431:38)

·           at eval (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:7612:44)

·           at cljs.core.LazySeq.sval (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:5561:40)

·           at cljs.core.LazySeq.cljs$core$ISeqable$_seq$arity$1 (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:5571:8)

·           at cljs.core._seq (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:2311:14)

·           at cljs.core.seq (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:2824:27)

·           at cljs.core.Cons.cljs$core$INext$_next$arity$1 (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:5383:51)

·           at cljs.core._next (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:2008:14)

·           at cljs.core.next (file:///C:/Functional_Languages/Clojure/LightTable/core/node_modules/lighttable/bootstrap.js:2851:150)

**Comment by kenny-evitt** [comment] 2015-11-15 20:31
@Brrrknee Sorry; I was responding to your report that drag & drop isn't working either.

With regard to opening a file of a type associated with LT, are you trying to open a file for which there's a space in its path? If so, would you try opening a file for which there isn't a space in the path?

**Comment by kenny-evitt** [comment] 2015-11-15 21:24
@Brrrknee I was able to open files of a type that I associated with LT from Windows Explorer on a Windows 7 computer; for files both with and without a space in their path.

The files however didn't open in an existing LT window. @cldwalker @rundis Is this a bug? Should opening a file associated with LT (on Windows) open the file in an existing LT window? Right now a new LT window is opened. Maybe that won't work because we allow multiple windows.

**Comment by cldwalker** [comment] 2015-12-02 07:10
@Brrrknee This is happening because the file you're trying to open does not [match this regex](https://github.com/LightTable/LightTable/blob/6cbc2d6c813ca36013f819e2383fa98f0faeb8ba/src/lt/objs/cli.cljs#L64). Without the specific file you're unable to open this is not reproducible and we'll have to close this.

**Comment by cldwalker** [comment] 2016-01-07 06:46
Closing because we can't fix this without the information requested.

**Closed by cldwalker** 2016-01-07 06:46 UTC
Labels: not-reproducible
