### ISSUE TITLE
Plugin install error message

### ISSUE THREAD

**Issue by rljohnsn** [LightTable/LightTable#1801] opened 2015-01-03 21:10 UTC
I get the below error messages for any plugin I install. 

![image](https://cloud.githubusercontent.com/assets/830382/5603718/3714dffe-9348-11e4-934d-99b9fc0b31f0.png)

Windows 8.1 (64bit)
Light Table Version: 0.7.2
Binary Version: 0.8.6

Plugins attempted:
RuboCop
Ruby
Ruby Instarepl
JSHint
Markdown

Plugins also do not appear to be installed
![image](https://cloud.githubusercontent.com/assets/830382/5603766/be3968b4-9349-11e4-968d-0c1cfdd5b57e.png)

**Comment by cldwalker** [comment] 2015-01-03 23:41
This is a duplicate of #1727. Do the plugins appear in the plugin manager?

**Closed by cldwalker** 2015-01-03 23:41 UTC
