### ISSUE TITLE
Ctrl-Space doesn't open command tab in a non-scrollable area

### ISSUE THREAD

**Issue by zarybnicky** [LightTable/LightTable#1897] opened 2015-05-01 13:59 UTC
Same as #674, #551.
On Windows 8.1, I've just downloaded a fresh LightTable 0.7.2 to try it out - in the 'Getting started' tutorial, I found that the first keybinding you write about doesn't work.

Same as in the previous issues, the tutorial is probably a browser tab under the hood.

**Comment by kenny-evitt** [comment] 2015-05-05 13:22
@snawster would you link to the "Getting started" tutorial you mention? Or tell me how you got to it? I'd like to reproduce this if I can. Also, if you could provide me with detailed steps with which *you* can reliably reproduce this issue, I'll see if I can too following the same steps.

**Comment by claudionebbia** [comment] 2015-06-01 16:35
I see that, on Windows 7, ctrl-space only work when you have a code tab on focus, if you have the console or the Docs tab on focus then it do nothing.

**Comment by kenny-evitt** [comment] 2015-06-08 14:47
@claudionebbia I can't reproduce the behavior you describe – <kbd>Ctrl</kbd>+<kbd>space</kbd> always opens the command bar for me, regardless of what has focus.

**Comment by kenny-evitt** [comment] 2015-06-08 14:48
@snawster please feel free to re-open this if you're still having the problem you described.

**Comment by snawster** [comment] 2015-06-08 15:25
I've tried again with the latest official (stable) release and I'm still having the problem.
On any in-app docs page or any in-app browser page, Ctrl-Space has the same effect as Space or PgDown.
If I click on Help->Documentation (topbar), Ctrl-Space opens Command bar as advertised. However, if I click anywhere into the docs pagepage

**Comment by cldwalker** [comment] 2016-01-08 05:39
I can't reproduce this on osx 10.10. I'll leave this open for a bit longer to see if other users run into this and can provide more info. Fwiw, I tried this in a browser tab, docs and intro tab

**Comment by cldwalker** [comment] 2016-01-26 06:24
Closing for reasons stated above

**Closed by cldwalker** 2016-01-26 06:24 UTC
Labels: not-reproducible, windows
