### ISSUE TITLE
Garbled Text in dialog box when trying to open file

### ISSUE THREAD

**Issue by bileshg** [LightTable/LightTable#2491] opened 2020-06-06 10:49 UTC
The problem is that whenever I try to open a file in it, the dialogue box shows garbled text.

Steps to reproduce the behaviour:
1. Go to the 'File' menu
2. Click on 'Open File'
3. Dialogue box opens

Expected behaviour: The dialogue box should contain readable text 

Please refer to the following screenshot
![Screenshot from 2020-06-06 13 51 34](https://user-images.githubusercontent.com/17637482/83942464-2365b580-a811-11ea-837b-96aaf0e89308.png)

Operating System: elementary OS 5.1.5 Hera

Additional context:
I recently installed the LightTable IDE on my Laptop which has elementary OS 5.1.5 Hera as the OS.

I installed it in the `/opt` folder and created a `.desktop` file for it in the `~/.local/shared/applications` folder so that I can open it from Applications.

The problem is that whenever I try to open a file in it, the dialogue box shows garbled text. Please refer to the attached screenshot.

**Comment by Mouvedia** [comment] 2020-06-24 08:20
dupe of #2343

**Closed as completed by Mouvedia** 2020-06-24 08:20 UTC
Labels: resolution: duplicate
