### ISSUE TITLE
LightTable 0.7.2 unresponsive in mac os X 10.7

### ISSUE THREAD

**Issue by dbrowne** [LightTable/LightTable#1902] opened 2015-05-04 01:28 UTC
1) Keyboard bindings do not work. 
2) Cannot quit application from Menu

**Comment by kenny-evitt** [comment] 2015-05-05 13:36
@dbrowne is the OS X version in this issue title correct? I ask because I can't run Light Table on my MacBook running OS X 10.6. [Light Table requires OS X 10.7 or newer.](http://docs.lighttable.com/#other)

**Comment by dbrowne** [comment] 2015-05-05 14:44
Sorry. Typo on my part is is 10.7

**Comment by kenny-evitt** [comment] 2015-05-05 15:41
@dbrowne thanks. Is LT always unresponsive after opening? If you would detail the steps you take when you observe this issue I will try to reproduce it.

**Comment by dbrowne** [comment] 2015-05-05 15:47
Start either from command line or via icon.  
Startup window appears. No options appear with any permutation of ctontrol keys and other keys
Menu quit does not quit application can only kill via pid or taskbar.

**Comment by kenny-evitt** [comment] 2015-06-20 14:48
@dbrowne For the next release (whenever that is), Light Table will be using Atom/Electron instead of node-webkit/NW.js. Unfortunately, Electron requires version 10.8+ of Mac OS X. I'm going to close this as it doesn't seem feasible to resolve.

**Closed by kenny-evitt** 2015-06-20 14:48 UTC
Labels: mac, not-reproducible
