### ISSUE TITLE
Segmentation fault (core dumped) when starting ./LightTable

### ISSUE THREAD

**Issue by ovidiugabriel** [LightTable/LightTable#2449] opened 2019-11-22 13:10 UTC
**Describe the bug**
Segmentation fault (core dumped) when starting ./LightTable

**Branch**
Downloaded from https://github.com/LightTable/LightTable/releases/download/0.8.1/lighttable-0.8.1-linux.tar.gz

**To Reproduce**
1. Extract lighttable-0.8.1-linux
2. change working directory to this one
3. Run `./LightTable` to start the editor

**Expected behavior**
Editor should start

**Actual behavior**
Segmentation fault (core dumped) message is visibile in the terminal.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version:5.3.11-100.fc29.x86_64  (Fedora 29 Workstation)

```
[New Thread 0x7fffe5890700 (LWP 31676)]
[Detaching after fork from child process 31677]
[New Thread 0x7fffe508f700 (LWP 31678)]
[New Thread 0x7fffe488e700 (LWP 31679)]
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments

Thread 1 "LightTable" received signal SIGSEGV, Segmentation fault.
0x00000000010c83eb in ?? ()
(gdb) bt
#0  0x00000000010c83eb in ?? ()
#1  0x00007ffff4d44073 in hb_font_funcs_set_nominal_glyph_func (ffuncs=0x370771a96420, func=0x7ffff54f16c0 <pango_fc_hb_font_get_nominal_glyph>, user_data=0x0, destroy=0x0) at hb-font.cc:638
#2  0x00007ffff54f1ee7 in pango_fc_get_hb_font_funcs () at ../pango/pangofc-shape.c:265
#3  _pango_fc_shape (font=<optimized out>, item_text=0x370771ac0710 "●", item_length=3, analysis=0x370771c580d0, glyphs=0x370771b0cca0, paragraph_text=0x370771ac0710 "●", paragraph_length=3) at ../pango/pangofc-shape.c:372
#4  0x00007ffff66985b8 in pango_shape_full (item_text=0x370771ac0710 "●", item_length=3, paragraph_text=<optimized out>, paragraph_length=3, analysis=analysis@entry=0x370771c580d0, glyphs=glyphs@entry=0x370771b0cca0)
    at ../pango/shape.c:116
#5  0x00007ffff6689c83 in shape_run (line=line@entry=0x370771c54cf0, state=state@entry=0x7fffffffc480, item=item@entry=0x370771c580c0) at ../pango/pango-layout.c:3242
#6  0x00007ffff668b6b6 in process_item (layout=layout@entry=0x370771c5b020, line=line@entry=0x370771c54cf0, state=state@entry=0x7fffffffc480, force_fit=force_fit@entry=1, no_break_at_end=no_break_at_end@entry=0)
    at ../pango/pango-layout.c:3355
#7  0x00007ffff668dd1d in process_line (state=0x7fffffffc480, layout=0x370771c5b020) at ../pango/pango-layout.c:3654
#8  pango_layout_check_lines (layout=<optimized out>) at ../pango/pango-layout.c:3982
#9  pango_layout_check_lines (layout=<optimized out>) at ../pango/pango-layout.c:3855
#10 0x00007ffff668ee6e in pango_layout_get_unknown_glyphs_count (layout=layout@entry=0x370771c5b020) at ../pango/pango-layout.c:1224
#11 0x00007ffff69a7112 in find_invisible_char (widget=<optimized out>) at gtkentry.c:2256
#12 0x00007ffff69aa355 in gtk_entry_init (entry=0x370771c590a0) at gtkentry.c:2279
#13 0x00007ffff616098a in g_type_create_instance (type=60505111641600) at gtype.c:1864
#14 0x00007ffff6143058 in g_object_new_internal (class=class@entry=0x3707719ec880, params=params@entry=0x0, n_params=n_params@entry=0) at gobject.c:1805
#15 0x00007ffff61447a5 in g_object_new_with_properties (object_type=60505111641600, n_properties=0, names=names@entry=0x0, values=values@entry=0x0) at gobject.c:1973
#16 0x00007ffff6145361 in g_object_new (object_type=<optimized out>, first_property_name=<optimized out>) at gobject.c:1645
#17 0x000000000196eaea in ?? ()
#18 0x0000000002f45a96 in brightray::BrowserMainParts::ToolkitInitialized() ()
#19 0x000000000229f7a7 in ?? ()
#20 0x00000000022a04eb in ?? ()
#21 0x0000000002298eed in ?? ()
#22 0x00000000010a7881 in ?? ()
#23 0x00000000010a6780 in ?? ()
#24 0x0000000002e6fa97 in main ()
```

**Comment by Mouvedia** [comment] 2019-11-22 19:42
duplicate of #2377 or #2378

**Closed by Mouvedia** 2019-11-22 19:42 UTC
Labels: linux, resolution: duplicate
