### ISSUE TITLE
Remote nrepl hijacks the instant evaluation

### ISSUE THREAD

**Issue by robjens** [LightTable/LightTable#2085] opened 2015-12-26 21:31 UTC
Since I couldn't find anything about it in any tickets, and found out myself rather 'late' (I've been using LT ever since 0.3 or so I think, quite frequently - that is hours per day for the past year and more) probably since I initially didn't use nrepl so much, but anyway. You do realize that using nrepl basically limits the editor to 1 single project use at that time, when it concerns instant evaluation right?

Meaning, I can easily have 2 Clojure projects run along each other in the same editor instance and do instant evaluation on each of them just fine. But as soon as a remote nrepl connection comes in, obviously, the editor has _no sense of which project it would belong to_, am I correct? I mean it could reasonably guess, perhaps, or if the nrepl service would expose data such as the pwd when run or just its coordinate perhaps, but I see how this is troublesome. It's not really something that can be coordinated with third parties and unless there is a way this information could be picked up, as is, from simply a hostname and a port number that I am aware of, I guess unfixable. Unless there will be an option later in LightTable, which would allow one to hook/connect/link a project and the files in it, to a nrepl connection.

The problem simply is, that any other file that is not suitable to run with the nrepl connection, will be evaluated in the context of the nrepl connection.

Is this something you guys are aware of, will be fixed at some point and/or I guess the solution in either way for now, would be in opening two editors, am I correct?

**Comment by kenny-evitt** [comment] 2016-01-04 16:56
@robjens I'm not sure exactly what the issue is. Would you mind providing explicit (and minimal) steps to reproduce it?

**Comment by cldwalker** [comment] 2016-01-07 06:40
Hi @robjens. Closing as there isn't a reproducible issue here. Can reopen if given a specific set of steps to reproduce a concrete issue

 I'll answer some questions below. For future reference, I'd recommended [asking questions in the mailing list](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#help)

> You do realize that using nrepl basically limits the editor to 1 single project use at that time, when it concerns instant evaluation right?

Each tab/file can associate with one connection by design. Multiple tabs/files can use the same connection. Instarepl should obey these connection rules like any other client

> But as soon as a remote nrepl connection comes in, obviously, the editor has no sense of which project it would belong to, am I correct?

You should be able to ctrl-eval any file in a project and have an nrepl connection associate with that given file. You can verify current connections with the `Show connect bar` command.

**Closed by cldwalker** 2016-01-07 06:40 UTC
Labels: not-reproducible
