### ISSUE TITLE
Evaluation don't work.

### ISSUE THREAD

**Issue by KarsFR** [LightTable/LightTable#2187] opened 2016-04-13 12:16 UTC
I have an error when I try to evaluate python code.

```
print("Hello, World!")
Traceback (most recent call last):
  File "/opt/LightTable/resources/app/plugins/Python/py-src/ltmain.py", line 193, in handleEval
    code= compile(ensureUtf(code), ensureUtf(data[2]["name"]), 'eval')
  File "/opt/LightTable/resources/app/plugins/Python/py-src/ltmain.py", line 50, in ensureUtf
    if type(s) == unicode:
NameError: name 'unicode' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/LightTable/resources/app/plugins/Python/py-src/ltmain.py", line 197, in handleEval
    code= compile(ensureUtf(code), ensureUtf(data[2]["name"]), 'exec')
  File "/opt/LightTable/resources/app/plugins/Python/py-src/ltmain.py", line 50, in ensureUtf
    if type(s) == unicode:
NameError: name 'unicode' is not defined
```

Lighttable 0.8.1-1 on Archlinux.

**Comment by rundis** [comment] 2016-04-13 13:17
This is a duplicate of https://github.com/LightTable/Python/issues/24
The python plugin needs a maintainer. The LT core team has stopped supporting the python plugin.

**Closed by rundis** 2016-04-13 13:17 UTC

**Comment by KarsFR** [comment] 2016-04-13 13:19
Okay, didn't see it.

Ty

**Comment by dexter1100** [comment] 2016-04-26 22:23
I also had this problem. Since searching for a solution didn't turn up anything useful I ended up editing my ltmain.py file, what the error message above is referring to. 
I just put a simple version checking in, since Python 3 strings are unicode by default they don't have to be converted. It's about 8 lines more than the previous version. 
I don't know how elegant this solution is but that's what I have and it works, although I only checked with simple things. Here it is: http://pastebin.com/2Q6KWM0W

**Comment by kenny-evitt** [comment] 2016-04-27 16:52
@dexter1100 There are some existing pull requests that address this too:

 - [Fixing compatibility with python3 by UnknownProgrammer · Pull Request #28 · LightTable/Python](https://github.com/LightTable/Python/pull/28)
 - [Pep8 and Python 3 compatibility by hayd · Pull Request #30 · LightTable/Python](https://github.com/LightTable/Python/pull/30)
 - [Changed unicode to str as Python3 does not use unicode by DChang87 · Pull Request #39 · LightTable/Python](https://github.com/LightTable/Python/pull/39)
 - [Python3 unicode - Fixing issue #24 -NameError: name 'unicode' is not defined by RockyRoad29 · Pull Request #47 · LightTable/Python](https://github.com/LightTable/Python/pull/47)

**Comment by dexter1100** [comment] 2016-04-28 10:10
I read some of them. I remember a particularly long conversation about converting between python3 and python2 strings which I didn't understand half of. That's why I chose to do a simple fix. Theoretically the plugin still should work with python 2 while fixing the unicode bug with python 3. 

Is there a way to show inline documentation for python (like with Clojure (Ctrl + d))?

**Comment by kenny-evitt** [comment] 2016-05-01 15:30
@dexter1100 There's *currently* no way to show inline docs for Python; that would need to be implemented in the plugin.
