### ISSUE TITLE
Clojure instarepl doesn't remove all intermediate results

### ISSUE THREAD

**Issue by Magos** [LightTable/LightTable#1804] opened 2015-01-05 07:37 UTC
Possibly related to #1324. When my lets involve multiple values, such as a for, map and so on, every evaluation creates more intermediate results. These do not go away with Editor:Clear inline results.
![image](https://cloud.githubusercontent.com/assets/1004386/5610339/fcb11016-94b5-11e4-8341-ffa627b78dc8.png)
Running LT 0.7.2 on Windows 7.

**Comment by cldwalker** [comment] 2015-01-05 13:44
Thanks for the screenshot. This is a duplicate of #1230

**Closed by cldwalker** 2015-01-05 13:44 UTC
