### ISSUE TITLE
Issue matching curly brackets when exists symbols in comments

### ISSUE THREAD

**Issue by kiquetal** [LightTable/LightTable#1742] opened 2014-11-21 12:18 UTC
![lighttable2](https://cloud.githubusercontent.com/assets/5652772/5142245/ee07cc64-715e-11e4-8977-bd380842b301.png)

OS:openSusSE 64 bits.
LT:0.7.2

**Comment by cldwalker** [comment] 2015-01-30 19:43
Closing since I can't reproduce this without more information

**Closed by cldwalker** 2015-01-30 19:43 UTC
Labels: nodejs, not-reproducible
