### ISSUE TITLE
Multiple leading/trailing spaces are collapsed to a single one in Instarepl

### ISSUE THREAD

**Issue by Biserkov** [LightTable/LightTable#1872] opened 2015-03-11 16:52 UTC
Windows 8.1 x64
LightTable 0.7.2
Clojure plugin 0.1.1

``` clojure
(def s "    a     ")  #'user/a
(count s) 10
s " a "
```

``` clojure
(def s2 "         ")  #'user/s2
(count s2) 9
s2 " "
```

**Comment by kenny-evitt** [comment] 2015-03-11 17:40
I'm just guessing, but I think this might be due to Light Table using an embedded browser for its GUI, i.e. multiple whitespace characters are being collapsed or consolidated because that's how HTML is intended to be rendered. Try a string like `"<pre>          </pre>"` to check my hypothesis.

**Comment by cldwalker** [comment] 2015-03-11 19:53
Thanks for the report. Closing this as it is a duplicate of LightTable/Clojure#16

**Closed by cldwalker** 2015-03-11 19:53 UTC
Labels: windows
