### ISSUE TITLE
can't paste

### ISSUE THREAD

**Issue by malkomalko** [LightTable/LightTable#537] opened 2013-05-06 14:42 UTC
running newest LT from command line on mac so that way it can see node.js executable and it doesn't seem to want to paste anything.  Looks like the menu item is firing but nothing pastes.

**Comment by cldwalker** [comment] 2015-03-06 16:04
I've [learned that OSX's clipboard does not work for processes](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard#mac-os-x-pasteboard-access-under-tmux-and-screen) under tmux and screen. You can verify this by trying to use pbpaste and pbcopy. Once I invoked LT master without a tmux-based shell my clipboard issue was resolved. Closing since using LT from tmux is not an LT issue. If someone is still having this issue with a non-tmux shell, please include reproducible steps that include your shell setup

**Closed by cldwalker** 2015-03-06 16:04 UTC
Labels: mac, nw
