### ISSUE TITLE
On Windows & Clojure: "ExceptionInfo: Unsupported escape character: \U"

### ISSUE THREAD

**Issue by tjg** [LightTable/LightTable#1928] opened 2015-06-25 13:31 UTC
Hi!

On Windows, somehow I get the system into a state where it keeps showing the same error, whenever you try to type anything: `clojure.lang.ExceptionInfo: Unsupported escape character: \U`

I'm pretty sure it has to do with `[:app :lt.objs.settings/pair-keymap-diffs]`.

**Light Table version:**
- 0.7.2 (Binary version: 0.8.6)

**Platforms:**
- Windows 7. (Can't reproduce on Mac.)

**Config:**
- In user.behaviors: `[:app :lt.objs.settings/pair-keymap-diffs]`

**Reproduce:**
- Make a file with a `.clj` extension, to force Clojure mode.
- Copy & paste the function from here: http://clojurebridge.github.io/curriculum/outline/functions.html#/4
- Hit enter a couple times, and try to type `(+ 2)` or something.

**Workarounds:**
- Enabling *"Instarepl: Make current editor an instarepl"* seems to get rid of it.
- Removing `[:app :lt.objs.settings/pair-keymap-diffs]` seems to work.

**Stacktrace:**
Full stacktrace: https://gist.github.com/tjg/7968e4fe2d2879fa244e

```clojure
clojure.lang.ExceptionInfo: Unsupported escape character: \U :: {:column 132, :line 40, :type :reader-exception}
       core.clj:4327 clojure.core/ex-info
reader_types.clj:238 ibdknox.tools.reader.reader-types/reader-error
     RestFn.java:439 clojure.lang.RestFn.invoke
      reader.clj:249 ibdknox.tools.reader/escape-char
      reader.clj:257 ibdknox.tools.reader/read-string*
      reader.clj:157 ibdknox.tools.reader/read-delimited
[snip...]
         eval.clj:18 lighttable.nrepl.eval/try-read
         eval.clj:22 lighttable.nrepl.eval/lined-read[fn]
       core.clj:4642 clojure.core/repeatedly[fn]
     LazySeq.java:42 clojure.lang.LazySeq.sval
     LazySeq.java:60 clojure.lang.LazySeq.seq
         RT.java:484 clojure.lang.RT.seq
[snip...]
```

**Comment by kenny-evitt** [comment] 2015-06-25 14:10
I can't reproduce this on Windows 7 running either your same version or the *atom-shell* branch version.

**Comment by tjg** [comment] 2015-06-25 14:25
@kenny-evitt Ok, will try to do a clean install. I've seen this on 3 different computers. (Two of which aren't mine, but a learner's.)

**Comment by hiredgunhouse** [comment] 2015-08-28 16:04
I have the same problem. I'm also on Win7 and learning Clojure and am constantly hitting this issue.
Also I can reproduce it with the steps @tjg provided.

**Comment by kenny-evitt** [comment] 2015-08-28 16:08
@hiredgunhouse Please build the latest version (of the *master* branch), try to reproduce, and let me know the result.

**Comment by hiredgunhouse** [comment] 2015-08-28 20:17
@kenny-evitt when I try building from latest I get this error:
```
Running "download-electron" task
>> Cannot find electron v0.22.1 from GitHub null
Warning: Task "download-electron" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by kenny-evitt** [comment] 2015-08-29 04:36
@hiredgunhouse #1958 will cover the `download-electron` build issue. I couldn't reproduce it just now.

**Comment by hiredgunhouse** [comment] 2015-08-29 07:56
@kenny-evitt 
That's exactly what I did in the meantime.
I run into some other problems with my setup, but managed to solve them and now my fresh build of LT seems to work fine (I also updated to latest lein and clojure 1.7.0) and now with a quick tests I cannot reproduce the problem.
I'll try a bit more later (I want to also try another machine) and let you know.

**Comment by hiredgunhouse** [comment] 2015-09-10 15:20
I just confirmed using another machine that this problem does not exist anymore (I used the binaries are created about 12 days ago on the original machine)

**Comment by rundis** [comment] 2015-09-10 18:00
Great. Tx

**Comment by cclaudiu81** [comment] 2015-11-03 10:45
same behavior: win7 + light-table.

**Comment by kenny-evitt** [comment] 2015-11-03 15:33
@cclaudiu81 Are you running the latest 0.8.0 (alpha) release? Can you consistently or always reproduce with the same steps in the original comment? What plugins, and what versions, do you have installed?

**Comment by cclaudiu81** [comment] 2015-11-03 22:17
hi @kenny-evitt 
light-table vs 0.7.2 (maybe i need to upgrade)
on win7 it is always reproductible(at least on my station)
thanks for the quick feedback

**Comment by kenny-evitt** [comment] 2015-11-05 13:02
@cclaudiu81 Try the new version and let me know if this is still an issue. There's no automatic upgrade tho (because of the transition to maintenance by the open source team).

**Comment by cclaudiu81** [comment] 2015-11-06 13:16
hi @kenny-evitt 
i had some time to update and migrate from 0.7.2 to 0.8.0 version on a win7 machine.
it seems that there are some plugins which generate this behavior, because after i applied the old plugins it seems that the problem came back to life.
"clojure.lang.ExceptionInfo: Unsupported escape character: \U :: {:column 88, :line 37, :type :reader-exception}"

the list of plugins i configured is:
AltTab,
ChomeTools,
clj-light-refactor,
gitlight
grunt
Javascript
JSbeautify
JSHint
Ling-with-editor
Opener
Reminisce
TernJS
Vim
VIm_Sleek
Workspace_Nav.

all of them are updated to the last version found on light-table repository.

**Comment by kenny-evitt** [comment] 2015-11-06 14:54
@cclaudiu81 Fantastic news – thanks! The next step would be to uninstall the plugins one-by-one until the problem can't be reproduced. Or maybe start over with a new LT install and *install* the plugins one-by-one (as some definitely don't entirely cleanup all of their changes). Once you've identified the problematic plugin(s), we can investigate further and better determine the root cause.

**Comment by rwobben** [comment] 2015-11-23 14:19
I see the same error on a clean install of light table 0.8.0-alpha on a Windows 7 machine. I did not install any plugin.  Just did lein new app test and load it into Light table with file > open folder

**Comment by kenny-evitt** [comment] 2015-12-03 22:37
@rwobben Would you mind commenting with all the info listed in [the Bugs section of the contributing doc](https://github.com/LightTable/LightTable/blob/master/CONTRIBUTING.md#bugs)?

Also, are you using a non-English keyboard or entering non-ASCII characters in files that are open in LT, or even just in folders to which you've added to a workspace in LT?

**Comment by gilch** [comment] 2016-04-14 21:32
This is probably due to backslashes in Windows paths, which would explain why you can't reproduce it on a Mac. Your project is probably in a subdirectory of "C:\Users\". Note the "\U". This might help narrow down the issue. I've been experiencing similar issues on Windows 10 with 0.8.1.

**Comment by kenny-evitt** [comment] 2016-04-15 00:13
@ghost I haven't been able to reproduce this on any of my Windows computers either.

**Comment by robjens** [comment] 2016-04-26 22:52
I have this problem on a Windows server instance, which would be 8.1. I can confirm indeed that the file (not project in this case) is in `C:\Users\...`. Latest LT download public release version, not development/git.

**Comment by kenny-evitt** [comment] 2016-04-28 13:28
I can't reproduce by eval-ing a (single) form in a Clojure file whose path contains a directory that starts with 'U'; nor with a file whose path is under *C:\Users\*.

Someone encountering this issue – please provide (extremely) detailed steps to reproduce, e.g. the exact paths on your computer where you're creating files, etc.

**Comment by robjens** [comment] 2016-05-16 10:08
@cclaudiu81 Thank you! The misbehaving plugin was `clj-light-refactor`! Solved here and explains why my Win 10 box didn't suffer this problem and the Server 2012 R2 did.

**Comment by rundis** [comment] 2016-05-16 13:53
@robjens You mind submitting an issue to clj-light-refactor if you haven't already done so. It hasn't recevived much love lately, but I'm planning on giving it at overhaul when I'm back coding clojure for a living agains soon :-)

**Comment by kenny-evitt** [comment] 2016-05-18 21:30
Given that this was never reproducible by any of the core team, I'm going to close this. I created a new issue for this in the clj-light-refactor plugin repo:

 - ["ExceptionInfo: Unsupported escape character: \U" on Windows · Issue #8 · rundis/clj-light-refactor](https://github.com/rundis/clj-light-refactor/issues/8)

This may be caused by other plugins as well. Feel free to create a new issue in the GitHub repo for those specific plugins and link to this issue.

For anyone still convinced or suspecting that the issue affects LT itself, please [uninstall LT completely](https://github.com/LightTable/LightTable/issues/1968), install the latest version, and confirm that you can reproduce this.

**Closed by kenny-evitt** 2016-05-18 21:30 UTC
Labels: bug, not-reproducible, windows
