### ISSUE TITLE
Instarepl doesn't use my existing connection

### ISSUE THREAD

**Issue by MasterMastic** [LightTable/LightTable#2295] opened 2016-11-24 11:40 UTC
I'm trying to use instarepl with my project but instead of using my project, it always creates its own connection.

Steps to reproduce:

1. Load a project folder and open a source file in the editor.
2. Connect to it with Ctrl+Enter.
3. Wait for connection to be completed.
4. Ctrl+Space, select `Instarepl: Open a clojure instarepl`
5. Wait, it's making a new connection again (undesired).
6. Try to evaluate `(require 'my-project.core)` anyway, which fails with `java.io.FileNotFoundException: Could not locate myproject/core__init.class or myproject/core.clj on classpath`.
7. Go to View -> Connections, see one connection for my project and another one called "LightTable-REPL" of type `lein-light-nrepl`.

I'm running Light Table 0.8.1 on Arch Linux x86_64.

**Comment by sbauer322** [comment] 2016-11-24 19:07
Though I don't have much experience with the Instarepl plugin, I am fairly sure that evaluation via Ctrl-Enter and Crtl-Shift-Enter are independent of the Instarepl plugin. They should be from the Clojure plugin. As such, they would likely have their own connections. 

Regarding the failure mentioned when evaluating a project with the Instarepl, is there a repository available to test this against?

**Comment by MasterMastic** [comment] 2016-11-25 08:22
@sbauer322 I only pressed those to establish a connection, it really has nothing to do with the plugin.

As for repository, `lein new` will do, as it's like this with any project.

**Comment by sbauer322** [comment] 2016-11-25 11:00
Thanks, I'll give it a try this weekend!

**Comment by MasterMastic** [comment] 2016-11-25 14:44
Thank you, @sbauer322 .
I've just now tested again on Windows 10 Pro x64 and the problem was reproduced.

**Comment by sbauer322** [comment] 2016-11-29 01:46
I was able to reproduce this problem. From what I gather, the Instarepl was meant largely for quick, small prototyping that does not make use of dependencies. It looks like the Instarepl has some severe limitations with regards to working with projects. 

Unfortunately, I don't have a solution and the plugin is in need of a maintainer... despite how popular it appears to be. As such, I am doubtful a fix will be inbound any time soon. That said, the Light Table team would be happy to assist anyone interested in working on the plugin.

The suggested work around would be to use the inline evaluations (e.g., `Ctrl-Enter` and `Ctrl-Shift-Enter`) rather than the Instarepl.

Relevant other issues:

- https://github.com/LightTable/ClojureInstarepl/issues/14
- https://github.com/LightTable/Clojure/issues/55
- https://github.com/LightTable/LightTable/issues/1997

**Comment by sbauer322** [comment] 2016-12-14 06:03
I am closing this issue as the Instarepl is limited with regards to accessing projects and because the problem concerns the Instarepl plugin rather than Light Table's core. 

Please feel free to open a separate issue in the Instarepl plugin's repo.

**Closed by sbauer322** 2016-12-14 06:03 UTC
