### ISSUE TITLE
VB is cut off on the bottom of the syntax list

### ISSUE THREAD

**Issue by mtaurone** [LightTable/LightTable#1649] opened 2014-10-07 05:24 UTC
When choosing a syntax from the command console, VB is currently cut off and cannot be properly seen. The issue is the scroll bar does not go all the way to the bottom, so the issue will transfer to whatever is at the bottom.

**Comment by kenny-evitt** [comment] 2016-02-01 22:19
@mtaurone @shamrin Would you confirm whether you're still having this problem on the latest version?

@cldwalker @rundis I can't reproduce this on a Windows 7 computer [T]. Can either of you reproduce this on any of your computers?

**Comment by cldwalker** [comment] 2016-02-01 22:40
I've been able to reproduce on osx. Hope to add more to this in a week

**Comment by mtaurone** [comment] 2016-02-02 05:49
Can confirm problem still exists as of Light Table version 0.8.0

**Comment by mtaurone** [comment] 2016-02-02 05:53
Disregard, problem fixed as of latest update. Discovered that it wasn't
updating on its own and remedied problem.

**Comment by Mouvedia** [comment] 2016-09-05 03:24
@cldwalker OP says it's fixed. Shouldn't this be closed?

**Comment by sbauer322** [comment] 2016-09-05 04:13
Closing as issue was fixed as of version 0.8.0 per the original submitter.

**Closed by sbauer322** 2016-09-05 04:13 UTC
Labels: bug, UI
