### ISSUE TITLE
Deleting/Adding plugin outside LightTable automatically gets recognized when LightTable starts

### ISSUE THREAD

**Issue by clojens** [LightTable/LightTable#1833] opened 2015-01-26 11:21 UTC
I've found, when deleting a plugin the 'crude' way of `rm -rf ~/.config/LightTable/plugins`, when LT picks up, it is supposed to be removed after 2 consecutive tries unsuccesfully, however it does not always seem to 'kick in' because many times I could click "Install missing" and close/fire-up LT and it would persist nonetheless.

One of the points here probably is that, although to a certain degree the fault tolerance and automated fallback behavior is correctly assumed to be in order here, somewhat control is lacking on behalf of the user.

It would probably be better to have as popup buttons: `cancel`, `remove plugin from cache` (or list or memory, whatever) and `install missing` in the sense that the second option really isn't a explicit option currently. Perhaps even, one could argue the 2 tries fallback is somewhat superfluous if you take 'saving the user actions / clicks per operation' in the fact that left way or right, they'll be forced to make a choice here anyway. Cancel presumes "not now but later again" where install missing implies "try now but don't arse me if you fail" and removal says "don't bother me ever again", I get the feeling this probably a better granularity for this case where we resort to a modal dialog anyway, meaning we seek the input/interaction explicitely - it would serve the user to get a better response by asking the right questions straight away.

That having said, there is also the issue of behavior reloading right after `uninstall` in the plugin manager. As in it will trigger the above described automated response of "Oops I found a plugin missing" (yes of course, I just removed it explicitely = "don't arse me ever again").

Given this and my current knowledge/skills, this is not something I've gotten into the code too much yet and, although lacking time might be a contribution I could confortably make later by pull request.

Felt it should be here as a ticket probably since this is 'bugged and to be discussed' behavior I'd think.

**Comment by cldwalker** [comment] 2015-01-29 03:41
This happens because we now track dependencies in the User plugin's plugin.edn and that only gets saved when a user uses the plugin manager - which is the expected workflow. If you'd like to add support for deleting outside the plugin manager, you'll need to define an app behavior that triggers on :post-init and calls [this plugin-manager behavior](https://github.com/LightTable/LightTable/blob/21fcb13c45a474fc011c7137eccde4e2662cec9b/src/lt/objs/plugins.cljs#L639-L645). This way of deleting plugins isn't something I'd encourage for most users but happy to leave this open if you're interested in adding this.

**Comment by cldwalker** [comment] 2016-01-16 07:51
Closing as removing a plugin and starting LT should only prompt twice at most for a removed plugin. Can reopen if there are reproducible steps on latest LT where reprompting is occurring more than twice

**Closed by cldwalker** 2016-01-16 07:51 UTC
Labels: enhancement
