### ISSUE TITLE
Python: Raises SyntaxError on module docstrings

### ISSUE THREAD

**Issue by untitaker** [LightTable/LightTable#1503] opened 2014-06-03 21:16 UTC
Hitting ``Ctrl+Shift+Enter`` in just about any submodule in https://github.com/untitaker/vdirsyncer yields the following error message, although the related code is completely valid:

    Traceback (most recent call last):
      File "/home/untitaker/projects/lighttable/deploy/plugins/python/py-src/ltmain.py", line 187, in handleEval
        code= compile(code, data[2]["name"], 'eval')
      File "sync.py", line 17
        '''
          ^
    SyntaxError: EOF while scanning triple-quoted string literal

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/untitaker/projects/lighttable/deploy/plugins/python/py-src/ltmain.py", line 191, in handleEval
        code= compile(code, data[2]["name"], 'exec')
      File "sync.py", line 17
        '''
          ^
    SyntaxError: EOF while scanning triple-quoted string literal

**Comment by carocad** [comment] 2015-04-23 21:02
I can confirm that this bug happens on a Lighttable version 0.7.2 (binary v0.8.6) on Ubuntu 14.04.
Steps to reproduce:
1 - Make a multiline docstring:
"""
bug
"""
2 -  add a global function evaluation
"""
bug
"""
print('test')

3 - Evaluate the whole file (Ctrl-Shift-Enter)

Note: If only the function is evaluated, everything is ok, bug a complete file evaluation "crashes". Weird enough, in my Lighttable the code before actually runs (you can see the 'test' been printed on the console), even thought it displays an error traceback as shown in #1889. 

Hope it helps,

Cheers

**Comment by kenny-evitt** [comment] 2016-01-06 17:52
We're moving all of the Python-specific issues to LightTable/Python, the repo for the Python plugin but this seems to be a duplicate of #1200 and LightTable/Python#40 is the issue I created in the plugin repo to replace it.

Let me know in a comment on this issue if this isn't a duplicate of #1200.

**Closed by kenny-evitt** 2016-01-06 17:52 UTC
Labels: python
