### ISSUE TITLE
Light table cant connect to check simple code

### ISSUE THREAD

**Issue by Cheshire453** [LightTable/LightTable#1565] opened 2014-07-18 14:54 UTC
I opened a simple "Hello World" file into Light Table, then Ctrl+Enter to check it. Every time it says cant connect, that its a syntax error. Someone help? :(

**Comment by kenny-evitt** [comment] 2015-01-14 17:13
@joshuafcole based on the last comment by @Cheshire453 this is a Windows issue.

@Cheshire453 would you check whether the code you're trying to run is Python 2 or 3 and also check, in Light Table, what version Light Table is using. See issue #1640 for details.

**Comment by kenny-evitt** [comment] 2015-03-06 15:22
@Cheshire453 @gbgg were you able to resolve this issue?

**Comment by kenny-evitt** [comment] 2015-07-01 23:58
I just ran into this issue with my own Clojure project. I'm running the latest *atom-shell*, via `script/ligh.sh`, on Ubuntu 14.04.

Running `lein clean` seems to (temporarily) resolve the issue.

I'm closing this as its a duplicate of #1052 (and #1401).

**Closed by kenny-evitt** 2015-07-01 23:58 UTC
Labels: windows
