### ISSUE TITLE
Misleading error message when uninstalling plugin

### ISSUE THREAD

**Issue by ShayMatasaro** [LightTable/LightTable#1944] opened 2015-07-19 11:23 UTC
using 0.8 from master.
when uninstalling light refactor i get the following msg:

Some plugin dependencies are missing.

We found that the following plugin dependencies are missing:
clj-light-refactor 0.1.6
Would you like us to install them?

**Comment by cldwalker** [comment] 2015-08-29 20:42
HI @ShayMatasaro. I've verified this issue. It is misleading message caused by behaviors probably kicking off out of order. Note the uninstall still works. Regardless, it is something we'll need to fix

**Comment by cldwalker** [comment] 2015-09-22 13:13
This is fixed on master

**Closed** 2015-09-22 13:13 UTC
Labels: bug, in progress
