### ISSUE TITLE
Does not do what it says on the tin.

### ISSUE THREAD

**Issue by richard-delorenzi** [LightTable/LightTable#2348] opened 2017-07-25 13:53 UTC
I just tried light table (0.8.1), for the first time. I was expecting something special.
First I tried python. At first I could not get it to work at all. Then I realised I need to keep pressing ctrl-enter. Is this what I have to do, to get basic feedback.

Then I tried html, I managed to get feedback in another tab, but I have to keep switching tabs. (I can drag a tab, but nothing happens. Does not move, nothing). 

So does it do anything. I have searched for videos, and found no good demonstrations (now I know why).

**Comment by sbauer322** [comment] 2017-07-25 14:01
I don't use either of those plugins currently, but it is possible that is
their intended behavior.

Both the Python and HTML plugins (and pretty much everything else) are in
need of maintainers and have not had much support for quite some time... so
the user experience may be lacking at this point.

Having split windows opened and being able to drag tabs around should be
possible. If you right click on the tab there ought to be a menu item for
"Move tab to new tabset".


On Tue, Jul 25, 2017 at 9:53 AM, richard-delorenzi <notifications@github.com

**Comment by sbauer322** [comment] 2018-04-19 02:01
Closing this issue as having to manually evaluate code with `ctrl-enter` or `ctrl-shift-enter` is fairly consistent and standard across plugins.

In previous versions, I recall there was some some sort of constantly running whole file eval, but it was removed at some point... perhaps I am thinking of the clojure instarepl.

**Closed by sbauer322** 2018-04-19 02:01 UTC
Labels: question
