### ISSUE TITLE
feature request: shell in a tab

### ISSUE THREAD

**Issue by dominictarr** [LightTable/LightTable#533] opened 2013-05-05 21:12 UTC
I want to run a test script and see the results in the console.
essentially, this could just be a shell expression.

but it is not a long lived process like an eval client,
and it probably produces stack traces in stdout that can be linked to lines of code in the editor.

for my purposes binding a key to a command that runs in the directory of the currently open file would work well. I may also want to configure this per directory/workspace?
or maybe just a way to run a shell command and see output in the console...

**Comment by kristofer** [comment] 2015-01-23 19:12
nope, we REALLY need a tab with a shell in it. closing this issue and the referencing #1687 and closing that one referencing this one, well...

+1 for a shell tab

**Comment by rafaeldias** [comment] 2015-03-23 22:57
+1

**Comment by Rmmichael95** [comment] 2015-09-22 02:21
+1

**Comment by uripatish** [comment] 2015-10-10 06:49
+1

**Comment by VanAxe** [comment] 2015-10-15 19:02
+1

**Comment by muhuk** [comment] 2015-11-07 09:55
+1

Pretty please make this a standard feature.

-----

I have found [LT-Opener](https://github.com/eldargab/LT-Opener) and will give it a try now.

**Comment by kenny-evitt** [comment] 2015-11-07 18:59
@muhuk Please create [a new issue in the repo for the LT-Opener plugin](https://github.com/eldargab/LT-Opener/issues/new). I suspect its not working because its behaviors file isn't in [the new flat syntax](https://github.com/LightTable/LightTable/commit/ecc0fd49d744ad29369cf531a5f622405511507d).

Or, before creating an issue, first try converting it to the new format manually. Here's [the corresponding commit for converting the behaviors file for the default HTML plugin](https://github.com/LightTable/HTML/commit/69c635e2a265275dd98f85fa180c84bf05b7fa81).

I created [an issue in the LT-Opener plugin repo about the behaviors file format](https://github.com/eldargab/LT-Opener/issues/5).

**Comment by eldargab** [comment] 2015-11-07 19:21
@muhuk Seems like you messed up with settings. `open(1)` is a standard utility on OS X, but not on linux. Anyway, js console in dev tools should give you enough information.

**Comment by kenny-evitt** [comment] 2015-11-07 20:03
@muhuk My bad – it's definitely not the behaviors file. The latest version continues to support the old format of those files.

**Comment by muhuk** [comment] 2015-11-07 20:20
> open(1) is a standard utility on OS X, but not on linux. 

OSX is based on Linux.

    $ which open
    /bin/open
    $ open --help
    Usage: open [OPTIONS] -- command

    This utility help you to start a program on a new virtual terminal (VT).

    Options:
    -c, --console=NUM   use the given VT number;
    -e, --exec          execute the command, without forking;
    -f, --force         force opening a VT without checking;
    -l, --login         make the command a login shell;
    -u, --user          figure out the owner of the current VT;
    -s, --switch        switch to the new VT;
    -w, --wait          wait for command to complete;
    -v, --verbose       print a message for each action;
    -V, --version       print program version and exit;
    -h, --help          output a brief help message.

**Comment by eldargab** [comment] 2015-11-07 21:08
@muhuk the `open(1)` command you refer to is a completely different thing. It has nothing to do with `open(1)` we have on OS X. Try to make sure that your command works as expected when entered directly, before attempting to configure the plugin.

**Comment by kenny-evitt** [comment] 2015-11-19 23:35
For anyone familiar with [Butterfly](http://paradoxxxzero.github.io/2014/02/28/butterfly.html) – can't it be used as-is by accessing it from a browser tab in LT?

**Comment by justintaft** [comment] 2015-11-20 07:01
@kenny-evitt I  made a butterfly plugin a while back,  I can open up a branch.  There some bugs but I can't remember what they were

**Comment by kenny-evitt** [comment] 2015-11-20 12:31
@justintaft What does your plugin do? Start Butterfly and open a browser tab in LT?

**Comment by babinc** [comment] 2015-11-21 03:11
+1 for shell in a tab!

**Comment by kenny-evitt** [comment] 2015-11-21 14:59
So I confirmed that you can in fact just use [Butterfly](http://paradoxxxzero.github.io/2014/02/28/butterfly.html) as-is – start it, open a browser tab in LT, and change the address of the browser tab to point to the Butterfly server. I'm not sure what value a plugin would add.

**Comment by kenny-evitt** [comment] 2015-11-21 14:59
So I confirmed that you can in fact just use [Butterfly](http://paradoxxxzero.github.io/2014/02/28/butterfly.html) as-is – start it, open a browser tab in LT, and change the address of the browser tab to point to the Butterfly server. I'm not sure what value a plugin would add.

**Comment by muhuk** [comment] 2015-11-21 18:26
@kenny-evitt it would reduce work from:

* start it
* open a browser tab in LT
* and change the address of the browser tab to point to the Butterfly server

to:

* open a shell tab in LT (with a bonus of recognizing project dir or file dir)

**Comment by kenny-evitt** [comment] 2015-11-21 19:39
@muhuk Yeah; I can see the value in that. And it can do other cools things too – see [the help info](https://github.com/paradoxxxzero/butterfly/blob/856aac2bcb5ffe0685f9a6905b66cd3a2fb7a349/butterfly/bin/help.py). [Something in particular that might be really handy](https://github.com/paradoxxxzero/butterfly/blob/856aac2bcb5ffe0685f9a6905b66cd3a2fb7a349/butterfly/bin/help.py#L33):

```
{title}Butterfly programs:{reset}
  {strong}b         : {reset}Alias for {strong}butterfly{reset} executable. Takes a comand in parameter or launch a butterfly server for one shot use (if outside butterfly).
...
```

**Comment by kenny-evitt** [comment] 2015-12-06 22:28
One thing I noticed about Butterfly, tho I didn't spend any real amount of time investigating it, is that the browser tab in LT pointing at Butterfly seemed to refresh automatically and lose my history. I'm not sure if there's a quick-fix for that or that's part of why the shell-in-a-tab feature needs to be more tightly bound to LT.

**Comment by alekseilunacharskii** [comment] 2016-02-29 14:36
Hello, I've invested some time to create a really simple wrapper around butterfly.
See here for details https://github.com/alun/terminal/blob/master/README.md
There of course some more work to do to make it more pleasant to use.

**Comment by kenny-evitt** [comment] 2016-09-03 14:03
I'm closing this as @alekseilunacharskii has implemented a plugin to provide this and any future work related to this can best be directed towards improving that plugin.

Thanks @alekseilunacharskii ! 🎉 👍 Sorry for not congratulating you back in February!

**Closed by kenny-evitt** 2016-09-03 14:03 UTC
Labels: plugin
