### ISSUE TITLE
Hyphens in code slow down Light Table

### ISSUE THREAD

**Issue by DeusSanctum** [LightTable/LightTable#2160] opened 2016-03-17 14:07 UTC
Hello,

Maybe I am missing something but when I write some code (Clojure code) and want to add some cosmetics separator as comments like

;;----------------Part 1-------------- 

[code]

When I try to write in place of "Part 1", Light Table freezes completely and I have to wait like 2 minutes before i can write into it. 

I'm under Windows 7

Thanks

**Comment by cldwalker** [comment] 2016-03-18 04:06
I can't reproduce this on osx 10.10. This may be a dupe of #2102. If you restart LightTable is this still an issue? If it is, can you provide the .clj file causing this?

**Comment by DeusSanctum** [comment] 2016-03-21 10:47
Hello,

Sorry for the late reply, here is a sample code where the problem can occur (as .txt because .clj does not upload) : 

[core-lt-prob.txt](https://github.com/LightTable/LightTable/files/182002/core-lt-prob.txt)

You can try by : 

- First : copy paste any ;; --- (ex : ";;---------------Config---------------")
- Then : try to erase "config" with "<--" and write

Light table freeezes.

Maybe it's not Ligh Table because it did it 3 times today but last time I tried no.

**Comment by cldwalker** [comment] 2016-03-26 14:53
Thanks for the example file. I'm able to edit that file and autocomplete in it fine. Since the problem has disappeared for you, I'm assuming this is a dupe of #2102. I have seen freezing occur when LT is open for many days. If you come across a reproducible case for freezing, feel free to add a comment there

**Closed by cldwalker** 2016-03-26 14:53 UTC
Labels: not-reproducible
