### ISSUE TITLE
Docs window is to small

### ISSUE THREAD

**Issue by ProjectINT** [LightTable/LightTable#2131] opened 2016-01-22 06:56 UTC
![screenshot from 2016-01-22 08 52 37](https://cloud.githubusercontent.com/assets/16366604/12504407/e2ae6cd8-c0e5-11e5-9b17-0fb10f66214a.png)

**Comment by cldwalker** [comment] 2016-01-22 09:08
Thanks for the report. That looks like an old version. Upgrading to 0.8.1 should fix this. You can also just moving the docs tab next to Welcome tab and close the empty tabset. Closing but if you have trouble the upgrade please give more info as asked in CONTRIBUTING.md

**Closed by cldwalker** 2016-01-22 09:08 UTC

**Comment by kenny-evitt** [comment] 2016-01-26 18:41
[Someone else reported this on Gitter.](https://gitter.im/LightTable/LightTable?at=56a77c8ceaf741c118d4f384)

But I couldn't reproduce this myself just now.

@ProjectINT What steps are you taking that result in the docs tab appearing like in your screenshot?

**Comment by Tuborgman** [comment] 2016-01-26 19:47
Hello! This is reproducible on OSX OSX 10.11.3.
Steps are simple:
1. Open the editor.
2. Click on the highlighted link "Light Table's online docs"
3. Observe the issue on the just opened right pane.
http://pasteboard.co/15ckPBxw.png

**Comment by kenny-evitt** [comment] 2016-01-27 23:18
I can't reproduce this [note to me – T] on a Windows 7 computer running a recent source build (at least as recent as version 0.8.1).

Interestingly, when I *left* click on the link, a new tab is opened – in the same tabset as the "Welcome" tab.

The docs tab is also named differently – my tab is named "Light Table docs". But in both of the screenshots provided by @ProjectINT and @Tuborgman, the tab is named "Docs".

@Tuborgman Did you close LT since you upgraded to 0.8.1? Would you try closing it and then confirm whether you can reproduce this afterwards?

**Comment by kenny-evitt** [comment] 2016-01-28 04:17
I was able to reproduce this on a Windows 10 computer [note to me – L] just now.

I was running 0.8.0. The Docs opened fine – old style.

I upgraded to 0.8.1. When I closed and re-opened LT and then clicked the docs link I got the shrunken docs tab in a new tabset.

**Comment by kenny-evitt** [comment] 2016-01-28 04:18
I just downloaded 0.8.1 from the website on the same Windows 10 computer. The docs link opens in a tab in the *same* tabset, and it's not shrunk.

**Comment by kenny-evitt** [comment] 2016-01-28 04:32
@cldwalker @rundis I ran a diff between the directories with the 0.8.0 and 0.8.1 versions of LT on my computer. The LT in the 0.8.0 directory *should* have been upgraded to 0.8.1. But *resources\app\core\node_modules\lighttable\cljs\lt\objs\docs.js* in the 0.8.0 directory doesn't match the one for 0.8.1. In fact, 38 files in that same directory don't match.

**Comment by Tuborgman** [comment] 2016-01-28 23:27
@kenny-evitt 
>> @Tuborgman Did you close LT since you upgraded to 0.8.1? Would you try closing it and then confirm whether you can reproduce this afterwards?

Sure - generally I'm not keeping it open all the time ) So this is reproducible after reloading the app.

**Comment by ProjectINT** [comment] 2016-02-04 03:34
0.8.1 fixed it for me, all looks fine.

**Comment by Tuborgman** [comment] 2016-02-04 04:46
0.8.1 is a version which has this issue at least on OSX 10.11.3.
