### ISSUE TITLE
How do I recover from a typo that was saved to User.Behaviors?

### ISSUE THREAD

**Issue by dmbennett** [LightTable/LightTable#1855] opened 2015-02-09 19:01 UTC
I was editing my user.behaviors as per the ruby instarepl github page. I inputed: [(:lt.objs.langs.ruby/use-rbenv)]

Now lighttable gets stuck on loading.

Is there a way to manually remove that command from the user.behaviors file?

**Comment by ibdknox** [comment] 2015-02-09 19:18
Depending on the OS, that file lives in:

OSX: ~/Library/Application Support/LightTable/User/user.behaviors
Linux: ~/.config/LightTable/User/user.behaviors
Windos: %APPDATA%\LightTable\User\user.behaviors

**Comment by cldwalker** [comment] 2015-02-20 16:02
Closing as this seems answered. Fwiw, if the typo was caused by a mismatched paren or bracket, you can enable [pair keybindings](https://github.com/LightTable/LightTable/wiki/FAQ#how-do-i-add-pair-keybindings) for English keyboards

**Closed by cldwalker** 2015-02-20 16:02 UTC
