### ISSUE TITLE
Copy&Paste from Console/Modals

### ISSUE THREAD

**Issue by kernelp4nic** [LightTable/LightTable#1809] opened 2015-01-08 03:07 UTC
Copy from Console with Cmd+C doesn't work (workaround -> right click/copy)
And from a modal (Browser External) doesn't work at all.

This are well-known behaviours? Couldn't find a similar issue.

Mac OSX 10.10.1
Lighttable 0.7.2
Without plugins

**Comment by cldwalker** [comment] 2015-01-30 20:01
On osx I can select any part of the console and copy with Cmd+C. Are you selecting a piece of text? By Browser External are you referring to one of the client buttons? It's a button so it's not expected to be copy-able.

**Comment by kernelp4nic** [comment] 2015-02-02 00:29
Sorry for the lack of detail,

Inside the console, If I tried the following:

* `CMD+A` + `CMD+C` -> doesn't work
* `MOUSE SELECT` +  `CMD+C` -> doesn't work
* `Right click` + `COPY` -> works
![light table](https://cloud.githubusercontent.com/assets/519481/5994596/7a244408-aa61-11e4-9527-83b8def76bd3.png)

By "Browser External" I mean: `Connect - Add connection` / `Browser "External"`:
![light table](https://cloud.githubusercontent.com/assets/519481/5994592/6d05fca8-aa61-11e4-9511-430dec07f4ab.png)
This text cannot be copied, you can select it, but `CMD+C` doesn't work and mouse right click is disabled.

**Comment by cldwalker** [comment] 2015-02-06 22:12
I'm not able to reproduce the copy issue with the "Browser External" modal. Are you using a binary of LightTable or are you running from a dev build e.g. master branch?

**Comment by kernelp4nic** [comment] 2015-02-07 02:20
uhm thats weird, I'm running the binary version updated through the app itself.

**Comment by cldwalker** [comment] 2015-10-28 04:50
We've released 0.8.0-alpha! - https://groups.google.com/forum/#!topic/light-table-discussion/rkfHTplo4ss. Closing as this should be resolved. Make sure you're not launching LT from tmux or screen as [explained in the FAQ](https://github.com/LightTable/LightTable/wiki/FAQ#are-there-limitations-to-copy-and-paste).  Ping us if it is still an issue

**Closed by cldwalker** 2015-10-28 04:50 UTC
Labels: not-reproducible
