### ISSUE TITLE
Behaviours reloading not working for skin change

### ISSUE THREAD

**Issue by anshbansal** [LightTable/LightTable#1980] opened 2015-09-14 17:23 UTC
Environment - Ubuntu 14.04 64-bit
Light Table version - 0.7.2
Binary version - 0.8.6

I followed the tutorial to the end. I changed the set skin to "light" but the whole thing did not turn white as expected and shown in the tutorial.

**Comment by anshbansal** [comment] 2015-09-14 17:29
I was able to get similar effect via 
 [:editor :lt.objs.style/set-theme "codemirror"]

But the tutorial should probably be changed.

**Comment by rundis** [comment] 2015-09-16 19:14
Duplicate of https://github.com/LightTable/LightTable/issues/1403

**Closed by rundis** 2015-09-16 19:14 UTC
