### ISSUE TITLE
Release version 0.8.0

### ISSUE THREAD

**Issue by kenny-evitt** [LightTable/LightTable#1936] opened 2015-07-02 14:37 UTC
This issue should cover all of the work that *needs* to be done before version 0.8.0 is released.

- [x] Add to [QA checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist)  _all_ features that should be QAed before a release
- [x] Finish 0.8.0 open issues
      - [x] #1715, #1781
      - [x] Replace all references to atom-shell with electron
      - [x] Add electron arch doc. Core contributors should feel empowered to make electron changes
- [ ] Figure out how to create an OSX signed 0.8.0 app. May require tweaks to script/build-app.sh @cldwalker
- [x] Cleanup repl process when LT quits #1961
- [x] Release windows as zip packages (via script/build-app.sh) @kenny-evitt 
- [x] Freeze master
- [x] QA using the above QA checklist
     - [x] Windows @kenny-evitt
     - [x] Linux @kenny-evitt and @cldwalker
     - [x] OSX @rundis
- [x] Add *0.8.0* milestone to all open issues that will be resolved for inclusion in this release.
- [x] Verify that future self-updates of LT will use GitHub (instead of Kodowa sites); and verify that updates actually work.
- [x] Release 0.8.0-alpha
      - [x] Version updates
         - [x] Decide on a version to release e.g. 0.8.0-alpha or 0.8.0 and update version.json.
         - [x] Make sure electron version is up to date in version.json
         - [x] Make sure plugin versions in script/build-app.sh are latest
      - [x] Each core developer should QA at least one OS using the [QA checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist)
      - [x] When QA passes freeze master
      - [x] Add changelog to GH release draft
      - [x] Upload binaries from script/build.sh to 0.8.0-alpha – don't forget to click *Save draft*!
         - [x] @kenny-evitt windows
         - [x] @rundis osx
         - [x] @cldwalker linux
      - [x] Publish release which also makes git tag
      - [x] Update download links on lighttable.com
      - [x] Mailing list announcement
- [x] For each pre-release, fix critical bugs and then cut a new prelease using steps in "Release 0.8.0-alpha"
- [ ] Release 0.8.0
      - [ ] Add entries to [the changelog](https://github.com/LightTable/LightTable/blob/master/deploy/core/changelog.md). We can just copy over what we have in the release notes.
      - [ ] Follow steps in "Release 0.8.0-alpha" :fireworks: :tada: :zap: :monkey_face:
      - [ ] Also blog post
- [ ] Have Chris [bump the kodowa endpoint](https://github.com/LightTable/LightTable/blob/0.7.2/src/lt/objs/deploy.cljs#L115) to 0.8.0. This is to let node-webkit users (who don't see announcements) to have LT auto-prompt them to download 0.8.0
- [ ] Add QA checklist to docs and release checklist to doc/for-committers.md
- [ ] Close all resolved issues: [fixed-on-master](https://github.com/LightTable/LightTable/labels/fixed-on-master), [nw](https://github.com/LightTable/LightTable/labels/nw) and 0.8.0 milestone issues

**Comment by kenny-evitt** [comment] 2015-07-02 14:55
It's only implied by one of the checklist items above, but [the previous release of Light Table is looking for updates at Kodowa endpoints](https://github.com/LightTable/LightTable/blob/0.7.2/src/lt/objs/deploy.cljs#L28-L31). The next release will use GitHub. Light Table won't be able to self-update. I thought this might be worth considering how to avoid, e.g. have someone at Kodowa upload the new release, but given that previous updates to the LT binary already couldn't be self-updated, I think this is a non-issue.

**Comment by cldwalker** [comment] 2015-08-24 12:51
@kenny-evitt Thanks for leading the charge on this! I hope to start helping on this when I can, starting with #1715

**Comment by cldwalker** [comment] 2015-08-24 13:03
@kenny-evitt I've updated the checklist and will add more when I think of em. @rundis Are you linux? If so could you be the linux QA?

**Comment by kenny-evitt** [comment] 2015-08-24 14:14
@cldwalker thanks for the additions.

My current focus for this has been writing an initial version of a Bash script to create the release packages for each environment (i.e. the *.zip* and *.tar.gz* files). I think I've got it working for Windows. I was going to work on the Mac portion next. I'm not sure what to do about the 32-bit Linux version as all my Linux boxen are 64-bit.

I've got at least one box for each of the environments and I recently replaced Windows (XP!) with Ubuntu 14.04 on my main personal computer. I have an old netbook and my main work computer both are running Windows 7.

**Comment by kenny-evitt** [comment] 2015-08-24 14:17
@cldwalker I just made [a PR for the 'package' script](https://github.com/LightTable/LightTable/pull/1954).

**Comment by kenny-evitt** [comment] 2015-08-24 14:21
@cldwalker Magnus (@rundis) and I previously agreed that releasing sooner would be better, e.g. for rallying community morale. I'm fine with deferring the release until we complete all of the items on our list, especially given your seeming ability to contribute more regularly of late, but I'd still like to release a 'pre-release' version ASAP, i.e. as soon as we can upload new 'release package' files to (GitHub) to be downloaded.

**Comment by rundis** [comment] 2015-08-24 17:55
@cldwalker I'm on mac. Could install a linux distro through parallells I suppose, but it would be smoke testing more than anything else though

**Comment by cldwalker** [comment] 2015-08-24 21:40
> My current focus for this has been writing an initial version of a Bash script to create the release packages for each environment (i.e. the .zip and .tar.gz files). I think I've got it working for Windows. I was going to work on the Mac portion next. I'm not sure what to do about the 32-bit Linux version as all my Linux boxen are 64-bit.

Before you spend too much time on this, what is the package script doing that [script/build-app.sh](https://github.com/LightTable/LightTable/blob/master/script/build-app.sh) doesn't do? A fair amount of work already went into it to make sure it works across platforms and mimics the existing packaging format. If there are issues with build-app.sh on windows we should fix em

@rundis Ok. Good to know

**Comment by kenny-evitt** [comment] 2015-08-27 13:26
@cldwalker The package script is just creating the *.zip* or *.tar.gz* files for users, or the update process, to download. The existing *build-app.sh* has an option to create the *.tar.gz*, but it didn't seem like the contents of the tarball it would create would match the latest download files nor would it create a *.zip* file for Windows or Mac users.

**Comment by kenny-evitt** [comment] 2015-08-27 13:29
For this task:

> Decide on a version to release e.g. 0.8.0-alpha or 0.8.0 and update version.json.

I think we should release *0.8.0-alpha*.

**Comment by cldwalker** [comment] 2015-08-29 15:08
@kenny-evitt Ok. Let's talk more about packaging tomorrow. Agree on 0.8.0-alpha
@kenny-evitt @rundis I've added a [QA Checklist](https://github.com/LightTable/LightTable/wiki/QA-Checklist) wiki page. Please feel free to update

**Comment by kenny-evitt** [comment] 2015-10-02 02:52
@rundis @cldwalker Regarding "Verify that future self-updates of LT will use GitHub (instead of Kodowa sites); and verify that updates actually work.":

 - Long-term, we shouldn't need to direct users to download the "binary version" from the main website anymore, right? We should be able to replace the binary (somehow) after requesting that the user restart – but let's definitely punt on that for this release.
 - We could (eventually) move to using Electron's automatic update features – [it seems pretty nice for Mac OS X and Windows.](https://github.com/atom/electron/issues/1479) I agree with the comments on that link that we should, ideally, use the various Linux package managers to distribute releases. We should definitely solicit help with this and I don't think there's any reason we need to do it now, soon, or even ourselves.

I'm going to work on testing the self-updates next.

**Comment by cldwalker** [comment] 2015-10-02 03:58
> Long-term, we shouldn't need to direct users to download the "binary version" from the main website anymore, right?

lighttable.com is a pretty well known site so we'll want to keep download links valid initially (for an official release). If it becomes a pain to update 3 download links we could consider linking to the github download page

> We should be able to replace the binary (somehow)

We have deploy.cljs to auto-updates non-binary releases. We'll have to write more code to achieve this. I think we have more pressing issues but feel free to open an issue if you're interested in this

> We could (eventually) move to using Electron's automatic update features

Interesting. That might be something to check out later though it will be disappointing for linux users. 

> we should, ideally, use the various Linux package managers to distribute releases.

Ideally yes but I'd rather not officially support that as we're pretty overloaded as is. Maybe one day...

> I'm going to work on testing the self-updates next.

Cool. We should probably add this to the QA checklist as we'll want to verify self-updates across os's.

**Comment by cldwalker** [comment] 2015-10-02 04:01
@rundis @kenny-evitt Do we want to freeze master and QA for an alpha release? I'm waiting on @ibdknox as we sort out osx cert issues but I don't think we need to block on it for pre-releases

**Comment by kenny-evitt** [comment] 2015-10-02 13:33
@cldwalker @rundis I'm fine with freezing master. We have "Add 0.8.0 milestone to all open issues that will be resolved for inclusion in this release" on the checklist above – I'm going to make a quick pass thru the open issues to check for anything that might be reasonable to address now but I'm very confident there's nothing like that.

**Comment by rundis** [comment] 2015-10-02 22:03
@cldwalker @kenny-evitt I'm fine with freezing master.

**Comment by cldwalker** [comment] 2015-10-02 22:25
@rundis Great. Assuming @kenny-evitt does windows, do you want to QA linux or osx? I'm fine doing anything

**Comment by cldwalker** [comment] 2015-10-04 15:43
It seems @kenny-evitt is doing linux. @rundis Go for osx. I'm fine picking up windows using virtualbox. I hope to get to it by next weekend.
Fyi, I've tagged the latest commit on master with an 0.8.0-alpha tag. We can always re-tag if we uncover any release blockers during QA

**Comment by kenny-evitt** [comment] 2015-10-04 15:50
@cldwalker I'll do Windows too sometime this week; no harm in overlapping.

@cldwalker @rundis Except for a few issues I ran into (and a more-thorough testing of the Emacs plugin), Linux seems good to go; especially for an alpha release.

**Comment by rundis** [comment] 2015-10-04 20:15
Ok. I'll give the qa checklist on osx a go as soon as I can this week.

**Comment by cldwalker** [comment] 2015-10-05 13:23
@kenny-evitt Ok. I'll probably do linux on VBox since we're overlapping
I deleted the 0.8.0-alpha tag just now as I forgot tags are used by our self-update system. For the record, 0.8.0-alpha is 683785fdf571d32e86aa9fd7e6e98204243207b3 and I'll add tagging to the checklist

**Comment by kenny-evitt** [comment] 2015-10-05 14:02
@cldwalker I was just going to ping you about the tag. I left LT open on my Windows box at work and it helpfully informed me that "There's a newer version of Light Table!".

Maybe we could check GitHub releases instead of tags for the auto-update?

**Comment by rundis** [comment] 2015-10-05 16:31
@cldwalker Yeah. Noticed an excited tweet about a new release of Light Table in my twitter stream.

**Comment by cldwalker** [comment] 2015-10-05 16:45
@kenny-evitt Since that's more work and it's not a blocker, I'm inclined to leave it alone for now. We can reconsider later
@rundis Yep. I emailed the group to let em know about the false alarm

**Comment by rundis** [comment] 2015-10-05 20:30
What should we do in terms of documenting breaking or potentially breaking changes from version 0.7.2 too 0.8.0 ? (Especially for plugin authors). Discovered that while testing node integration through one of my early plugins (instabuster) was broken due to removal of lt.objs.thread.node-exe. Easy fix, but would be nice if we were somehow able to document breaking changes in the api (whatever we may consider to be the public api of LT for plugins that is).

**Comment by kenny-evitt** [comment] 2015-10-05 21:16
How feasible is it for us to figure out what's changed in the 'public API' since 0.7.2?

**Comment by kenny-evitt** [comment] 2015-10-05 21:17
Maybe the 'alpha' modifier for this release absolves us of any breaking changes and we make documenting any breaking changes (or unbreaking them) part of the stable release process.

**Comment by cldwalker** [comment] 2015-10-05 21:46
@kenny-evitt @rundis I can include a list of removed fns in a plugin authors section for the release email. I already have some other notes we'll need to mention to plugin authors. The release email will be rather long so at some point I'll put up a copy for review. I could start a wiki page for it if that helps

**Comment by kenny-evitt** [comment] 2015-10-05 22:03
@cldwalker Wiki page or file in source for the release email would be great.

**Comment by kenny-evitt** [comment] 2015-10-05 22:23
@cldwalker @rundis QA for Windows is done. Except for minor issues, e.g. #2000, #2005, everything seems to be working.

I think #2002 (i.e. problems with some plugins) can be addressed after the alpha release.

**Comment by rundis** [comment] 2015-10-06 08:11
I'm almost done with Mac OS X (maverick that is). I'll summarize my findings when done. Hopefully tnight.

**Comment by rundis** [comment] 2015-10-06 08:15
Btw: Would be great if we could use this room (restricted to commiters) for discussions that might not be all that interesting to everyone or a particular issue: https://gitter.im/LightTable

**Comment by rundis** [comment] 2015-10-06 21:24
Ok. QA for OS/X pretty much done I think. Everything seems to be working pretty nicely, which isn't a huge surprise as I've been through a lot of the items on the checklist fairly regularily when using LT on OS/X from master on my previous project.

@kenny-evitt @cldwalker  If you can't fault this pull: #2008 , I think it's worth including in the alpha release as it's a regression and gives uncessary "bad press" for something most clojure/javascript etc users would typically do regularly in LT.

**Comment by cldwalker** [comment] 2015-10-10 19:49
@rundis I've added a comment to #2008. I'm inclined to hold off after alpha release unless you have more insight and we want to delay the alpha release.

@kenny-evitt @rundis I've put up [this release email gist](https://gist.github.com/cldwalker/3d67153fe1eade2ae3cf). Please fork/comment and I'll merge/update. I've also created a draft release under https://github.com/LightTable/LightTable/releases with a full changelog. I didn't link directly b/c the url changes with every draft save. Feel free to add changes I've missed. I'm going to QA linux tomorrow. Assuming QA on my end is fine, when would you all prefer a release? I could do Monday but I can't do next weekend. The only remaining steps are outlined on the above "Release 0.8.0-alpha" step - basically we each upload one binary, click Publish and announce

**Comment by rundis** [comment] 2015-10-11 18:58
@cldwalker Tried to sweeten it, but I don't have a much stronger case for #2008 than previously. Tldr; I'll leave it to your good judgement

The release log looks good. Thx for the great effort. I'll have a closer look and try to consult my memory if anything of importance is missing.

I'm fine with Monday or any other day this week, but do keep in mind the time difference so ensure I've done my part/binary before launching.

Exciting times !

**Comment by cldwalker** [comment] 2015-10-13 06:13
I QAed linux and am fairly happy with it and only found #2017. I did notice on VirtualBox Ubuntu, LT would start up with a message that looked ominous "Running without the SUID sandbox" but Electron people say this is to be expected - https://github.com/atom/electron/issues/1482

I did notice that self-updates won't work for prereleases e.g. `(deploy/is-newer? "0.8.0-alpha" "0.8.0")`. This means that users who install alpha won't get an update prompt unless we upgrade electron. I'm inclined to upgrade electron to workaround this for now.

I don't think we'll get a release out this week as I'd like to vet #2008 some more and by the time that is done and we all upload binaries it will be close to the weekend. I'll be offline this weekend so hopefully next week

**Comment by cldwalker** [comment] 2015-10-22 06:27
Once #2008 is merged, I'll upload a linux version to the release draft. @kenny-evitt @rundis Can you each upload your respective OS's as well after #2008 is merged? If we get those all in, can we do a Friday/Saturday release? If it's too hard to coordinate a time, I'm happy to do the release (just a couple of steps). Also happy to hang out in gitter and we can chat through it

**Comment by rundis** [comment] 2015-10-22 17:48
#2008 Merged. I'm off-line pretty much all of friday. I'll try and get the binary uploaded in the next few hours.

**Comment by kenny-evitt** [comment] 2015-10-22 21:16
I'll upload a binary now for Windows.

**Comment by kenny-evitt** [comment] 2015-10-23 00:20
@cldwalker Is "Core developers QA two environments" in the checklist redundant?

Binaries for all three platforms have been uploaded to the draft release.

**Comment by cldwalker** [comment] 2015-10-23 04:59
@rundis Thanks. I imagine the bug reports won't start coming in until the weekend ;)
@kenny-evitt Thanks. I've re-uploaded linux as it's good if we each do one platform. Do you want to coordinate a time (12-1pm or after 5pm) on gitter or should I pull the trigger whenever I can tomorrow?

@rundis @kenny-evitt When you get the chance, could you state what OS version you built the binaries with? What to do you think about adding that at the bottom of each release? Would be useful history. I built linux on Ubuntu 14.04 on a VirtualBoxVM

> Binaries for all three platforms have been uploaded to the draft release.

@kenny-evitt Good point. I've removed it.. I've also updated the checklist to better organize what needs to be done per release and what we need to do up to and including 0.8.0.

**Comment by rundis** [comment] 2015-10-23 05:36
maybe "Core developers QA two environments", means downloading and trying the binaries you didn't upload yourself (smoke testing) in that context ? Not sure.

**Comment by kenny-evitt** [comment] 2015-10-23 13:45
@cldwalker I have an open-ended obligation all day tomorrow, but I could still probably meet on Gitter sometime after 5p. I'll gladly help out with anything so let me know when you want me to meet you in Cyberspace.

The Windows package was built on a Windows 7 box. I built the Linux package also on a Ubuntu 14.04 (physical) box.

**Comment by cldwalker** [comment] 2015-10-23 16:35
@kenny-evitt How about 5 or 5:30pm? I may need to be offline by 6pm

**Comment by kenny-evitt** [comment] 2015-10-23 21:47
@cldwalker Either time works for me. I'll make sure I'm available by 5p.

**Comment by cldwalker** [comment] 2015-12-11 00:23
Done! :tada:

**Closed by cldwalker** 2015-12-11 00:23 UTC
