### ISSUE TITLE
OS X Yosemite + bash it

### ISSUE THREAD

**Issue by andriytyurnikov** [LightTable/LightTable#1885] opened 2015-04-08 20:50 UTC
I have no idea how https://github.com/Bash-it/bash-it can possibly affect LightTable, but it looks like it does
Here the error message:
```
Error: Error: Command failed: /Users/andriytyurnikov/.bash_it/lib/helpers.bash: line 76: `bash-it': not a valid identifier
is not ISeqable
    at Error (<anonymous>)
    at cljs.core.seq (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:2833:11)
    at cljs.core.empty_QMARK_ (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:3693:62)
    at eval (file:///Applications/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:31483:32)
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.eval (child_process.js:950:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.eval [as close] (net.js:466:12)
```

and here is first 80 lines of file mentoned `cat /Users/andriytyurnikov/.bash_it/lib/helpers.bash`
(I think it is somehow about line#32)
:
```bash
# Helper function loading various enable-able files
function _load_bash_it_files() {
  subdirectory="$1"
  if [ ! -d "${BASH_IT}/${subdirectory}/enabled" ]
  then
    continue
  fi
  FILES="${BASH_IT}/${subdirectory}/enabled/*.bash"
  for config_file in $FILES
  do
    if [ -e "${config_file}" ]; then
      source $config_file
    fi
  done
}

# Function for reloading aliases
function reload_aliases() {
  _load_bash_it_files "aliases"
}

# Function for reloading auto-completion
function reload_completion() {
  _load_bash_it_files "completion"
}

# Function for reloading plugins
function reload_plugins() {
  _load_bash_it_files "plugins"
}

bash-it ()
{
    about 'bash-it help and maintenance'
    param '1: verb [one of: help | show | enable | disable ]'
    param '2: component type [one of: alias(es) | completion(s) | plugin(s) ]'
    param '3: specific component [optional]'
    example '$ bash-it show plugins'
    example '$ bash-it help aliases'
    example '$ bash-it enable plugin git'
    example '$ bash-it disable alias hg'
    typeset verb=${1:-}
    shift
    typeset component=${1:-}
    shift
    typeset func
    case $verb in
         show)
             func=_bash-it-$component;;
         enable)
             func=_enable-$component;;
         disable)
             func=_disable-$component;;
         help)
             func=_help-$component;;
         *)
             reference bash-it
             return;;
    esac

    # pluralize component if necessary
    if ! _is_function $func; then
        if _is_function ${func}s; then
            func=${func}s
        else
            if _is_function ${func}es; then
                func=${func}es
            else
                echo "oops! $component is not a valid option!"
                reference bash-it
                return
            fi
        fi
    fi
    $func $*
}

```

**Comment by kenny-evitt** [comment] 2015-04-09 15:50
@andriytyurnikov please add steps to reproduce this.

**Comment by andriytyurnikov** [comment] 2015-04-09 16:12
@kenny-evitt it is right there after LightTable start:
OS X Yosemite, with bash as a shell and bash-it installed
(screenshot)[http://cl.ly/image/2V28182e3t0i]

Launching LightTable executable from SpotLight

**Comment by kenny-evitt** [comment] 2015-04-09 16:29
@andriytyurnikov ahhh – interesting. This seems to be the same issue as #1277. Based on [this comment](https://github.com/LightTable/LightTable/issues/1277#issuecomment-36441727) on that issue, this is a problem with Node not ignoring what are technically invalid bash identifiers, e.g. `bash-it` (because of the hyphen).

**Comment by kenny-evitt** [comment] 2015-09-02 23:27
Duplicate of #1277

**Closed by kenny-evitt** 2015-09-02 23:27 UTC
