### ISSUE TITLE
0.8-alpha: not able to connect to clojure projects on windows (7)

### ISSUE THREAD

**Issue by rundis** [LightTable/LightTable#2027] opened 2015-10-26 19:36 UTC
Context: Windows 7, java 8, fresh install of lt 0.8 alpha

- created a simple project using lein new compojure hello-world
- tested with lein ring server-headless on commandline
- add project to workspace and try to eval handler.clj
- It reports it connecting, but after retrieving dependencies it silently drops out
- The javaprocesses are left running (the runner and the actuall nrepl'ed project)
- The lt log (windowx.log) just reports happily that nrepl is listening on port xxxxx

Pretty much same problem when trying to connect to the user plugin

**Comment by kenny-evitt** [comment] 2015-10-29 13:40
I just downloaded the 0.8.0-alpha release to my main Windows 7 computer and I had no trouble connecting to my existing Clojure/Compojure project.

I wasn't able to reproduce not-connecting with the same steps you took. I don't know what I can do to test that the project is *working* per-se but LT reports that it's connected to it, and no errors were reported.

I also had no problem connecting to or running a command defined in the user plugin.

@rundis Are you running Windows under Parallels on a Mac to reproduce this?

**Comment by cldwalker** [comment] 2015-12-05 14:50
@rundis Is this still an issue?

**Comment by cldwalker** [comment] 2016-01-08 01:11
@rundis Closing as @kenny-evitt can't reproduce. If you have more to add to  this, we can reopen in Clojure plugin

**Closed by cldwalker** 2016-01-08 01:11 UTC
Labels: bug, clojure, windows
